### ISSUE TITLE
Google listing & ads plugin disable jquery

### ISSUE THREAD

**Issue by ghost** [woocommerce/google-listings-and-ads#1044]
Hello there, 

I am using Google listing & ads plugin which is developed by woo commerce, i have few issues.

1. I use google listing & ads plugin with api integration so google merchant center pull product automatically from production.  when i copy site from production into staging. again all product pull from staging and make duplicate into google merchant center. 
2. if i disconnect all accounts in staging it will automatically disconnect from production. 
3. if i deactivate/delete google listing & ads plugin into staging then its disable jQuery some functions not working in my site

please advise how to handle this.

**Comment by juliaamosova** [comment]
Hi @haja-rr-dev,

Thank you for reporting the issue. It looks like the issue is on the [Google Listings & Ads](https://woocommerce.com/products/google-listings-and-ads/) plugin side of things. This plugin is being developed in another repository: https://github.com/woocommerce/google-listings-and-ads. 

I am going to move your bug report there so that the right team could take a look further.

**Comment by ghost** [comment]
Any updates regarding this ?

**Comment by ghost** [comment]
May i know how long it will take to fix approx. ?

**Comment by nima-karimi** [comment]
Hi @hajakutbudeen-dev 👋 

This repository is not intended for support requests. The best place to get support is the [WordPress.org Google Listings and Ads forum.](https://wordpress.org/support/plugin/google-listings-and-ads/)

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

> I use google listing & ads plugin with api integration so google merchant center pull product automatically from production. when i copy site from production into staging. again all product pull from staging and make duplicate into google merchant center.

> if i disconnect all accounts in staging it will automatically disconnect from production.

The behaviors described above are both expected. Google Listings & Ads uses WooCommerce Connect Server to interact with Google's APIs. When you connect your Google account, GLA passes the account information through to the WooCommerce server, which in turn passes that along to Google API. This means that, as long as you have the same Google account connected, you will get the same results and the same set of products on both of your websites. When you disconnect your Google account from any website, you are in fact also disconnecting it from the WooCommerce Connect Server; therefore, any other instance of GLA that you have set up using that account will also lose their connection because they all interact with WooCommerce Connect Server. You can try using another Google account on your staging server to get around this.

I hope that explains the situation. Please contact our happiness engineers through the channels I posted above regarding your third issue and provide them a copy of your System Status. You can find it via `WooCommerce > Status`. Select “Get system report” and then “Copy for support”.  They will be able to help you resolve that issue more quickly.

**Comment by ghost** [comment]
Thanks for your replay @nima-karimi
