### ISSUE TITLE
Conflict with “Advanced Coupons for WooCommerce Free” Plugin

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1059]
Noticed a report from a user [in the support forums](https://wordpress.org/support/topic/conflict-with-advanced-coupons-for-woocommerce-free-plugin/) that GLA is conflicting with "[Advanced Coupons for WooCommerce Free](https://wordpress.org/plugins/advanced-coupons-for-woocommerce-free/)"

I haven't had time to replicate, creating an issue to follow up. I've asked for additional information in case it is needed.

**Comment by chriseilander** [comment]
Having the same problem, disabling the "Advanced Coupons for WooCommerce Free" makes it possible to get into the setup. When that plugin is enabled it just generates a blank page on the admin backend.
[woo system.txt](https://github.com/woocommerce/google-listings-and-ads/files/7511571/woo.system.txt)

I've also set wp-debug to true, but it didn't generate a message on screen. Also no debug log file is generated when setting wp_debug_log to true.

The plugin places some items in the Marketing sub menu, but some items redirect to the Coupons submenu.

**Comment by ianlin** [comment]
I was looking into this problem yesterday with @eason9487 and he found this is because of the plugin [Advanced Coupons for WooCommerce Coupons][acfw] (**ACFW**) uses [wp_enqueue_script][wp-enqueue-script] to [register their script that depends on `wc-admin-app`][acfw-code].

According to [wp_register_script's document][wp-register-script-more-info], it says:

> Scripts that have been pre-registered using wp_register_script() do not need to be manually enqueued using wp_enqueue_script() if they are listed as a dependency of another script that is enqueued. WordPress will automatically include the registered script before it includes the enqueued script that lists the registered script’s handle as a dependency.

That is, since **ACFW**'s script depends on `wc-admin-app`, it somehow changes the scripts loading order so the `wc-admin-app` is loaded before `Google Listings and Ads`'s script. It leads to the [callback function of `addFilter`][gla-add-filter-cb] is not called then the page is left blank.

We also tested it with [Pinterest for WooCommerce][pinterest-woo] and the same problem happened to it as well.

I think it might be better to ask the development team of **ACFW** to solve this issue, @jconroy what would be the best way to open an issue for third-party plugin developers?

Thanks @eason9487 by the way!

[acfw]: https://wordpress.org/plugins/advanced-coupons-for-woocommerce-free/
[wp-enqueue-script]: https://developer.wordpress.org/reference/functions/wp_enqueue_script/
[acfw-code]: https://plugins.trac.wordpress.org/browser/advanced-coupons-for-woocommerce-free/trunk/Models/Upsell.php#L910
[wp-register-script-more-info]: https://developer.wordpress.org/reference/functions/wp_register_script/#more-information
[gla-add-filter-cb]: https://github.com/woocommerce/google-listings-and-ads/blob/82af1cf39c8bafee46a2acca1e36031d0f3de7bd/js/src/index.js#L34
[pinterest-woo]: https://github.com/woocommerce/pinterest-for-woocommerce

**Comment by findingsimple** [comment]
Hi @jkohlbach 👋 was stalking ACFW and was wondering if you would be a good person to loop into this conversation?

(also not sure if we've ever crossed paths in WP Aus community 👋 )

**Comment by jkohlbach** [comment]
G'day, yes, Advanced Coupons, that's us!

Let me get the team to take a look and we'll see what we can do on this end.

**Comment by jkohlbach** [comment]
Hey all, first thanks for including me here in this discussion – hit me up on WooCommerce Slack @jconroy! Would be great to connect.

Seems after some testing, looks like we're able to drop the wc-admin-app dependency on that script in Advanced Coupons. Seems we added it so we'd know the admin app was loaded so we could then do our thing.

We'll take care of this on an upcoming patch but i'm not sure when that'll be as we have 3.1 just around the corner. So likely after that.

For now, two options for anyone coming across this thread:
1. Deactivate then run the setup of Google Listings & Ads, then reactivate Advanced Coupons
2. Or, add the following to your functions.php or a custom plugin:
`remove_action('acfw_after_load_backend_scripts', array(\ACFWF()->Upsell, 'enqueue_upgrade_settings_scripts'), 10, 2);`

Let me know if I can help otherwise!

**Comment by jkohlbach** [comment]
Cheers also to @ianlin and @eason9487 for their excellent detective work. 谢谢你，朋友们!

**Comment by findingsimple** [comment]
Thanks so much for dropping in @jkohlbach love your work.

I'll close this issue for now as your team is taking care of things.
