### ISSUE TITLE
Persist Phone Number and Country Code after clicking edit

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1099]
## User story

As I user I want to be able to click edit and modify my phone number without re-filling it. 

![ezgif-4-d8ffff68d7c0](https://user-images.githubusercontent.com/5908855/142249663-0f566ee8-84e8-4848-b462-bb13a073edfe.gif)

## Steps to reproduce

1. Onboarding - Setup Merchant page
2. Go to the final step Confirmation
3. Insert your country code and phone number
4. Click on "Verify phone number"
5. Click edit
6. **Phone and country code are lost**

## Acceptance criteria

1. Onboarding - Setup Merchant page
2. Go to the final step Confirmation
3. Insert your country code and phone number
4. Click on "Verify phone number"
5. Click edit
6. **Phone and country code are there**

**Comment by mikkamp** [comment]
Just wanted to add a clarification:

If the MC account already has a verified phone number and we reach this step and click edit, then the country / phone number is pre-populated.

However if we do not have a verified phone number (scenario described in this issue), and we enter an initial number and then click on "send verification code". If we realize there that the phone number should be edited (because of a typo) it does not persist, so we have to again add the country and full phone number.

**Comment by mikkamp** [comment]
Phone number verification is being removed in #2653 so I'm closing this issue as no longer applicable.
