### ISSUE TITLE
Poor plugin performance

### ISSUE THREAD

**Issue by smazur** [woocommerce/google-listings-and-ads#1205]
### Describe the bug:
Hi there!

After installing Google Listings & Ads plugin i noticed performance degradation on the site. The TTFB difference is about +200ms when plugin is active and inactive. I have used xdebug profiler to find the bottleneck and found that plugin initialization stage takes from 40% to 60% of runtime.

https://drive.google.com/file/d/163-qbhtoAaktznTLFThx1JMmUu0xTwwF/view?usp=sharing

Thanks for any help.

**Comment by mikkamp** [comment]
Thanks for the report @smazur 
Do you have any additional details about what type of request you recorded there, is it a frontend (general WordPress page or WooCommerce page) or a backend request?

Could you also provide some details about your environment? Some details from a [WooCommerce System Status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1) would be helpful.

**Comment by smazur** [comment]
@mikkamp 
The issue appears on both front- and backend.

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): ...
Site address (URL): ...
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 7.4.27
PHP Post Max Size: 250 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.1j

SUHOSIN Installed: –
MySQL Version: 5.7.36-0ubuntu0.18.04.1
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: jt_
Total Database Size: 10079.01MB
Database Data Size: 5139.16MB
Database Index Size: 4939.85MB
...

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (60) ###

Advanced Cron Manager: by BracketSpace – 2.4.2
Anti-spam: by webvitaly – 5.5
Classic Editor: by WordPress Contributors – 1.6
CMB2: by CMB2 team – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.5.3
FBTH Email Activation: by TIV.NET – 14.01.29
FBTH Admin Help: by alexgff – 14.06.06
TIVWP Admin Search Extend: by TIV.NET – 14.5.22
FBTH Comment Ratings: by alexgff – 15.03.16
FBTH Cron: by TIV.NET – 14.04.04
FBTH Follow: by slaFFik – 13.10.16
FBTH Intercom Events: by Mazur Stanislav – 0.2
FBTH Knowledgebase: by alexgff
Stanislav Mazur – 20.7.1

FBTH Liker: by alexgff – 14.08.15
TIVWP User actions logging: by TIV.NET – 13.12.12
TIVWP Payoneer integration: by TIV.NET – 21.01.15
Fabthat Product Sets: by Stanislav Mazur – 0.0.1
TIVWP Rank: by TIV.NET – 99.99.99
FBTH Shop Pagination: by alexgff – 14.07.21
FBTH Submit Design: by TIV.NET – 0.1.0
FBTH Woocommerce Smart Email Testing Center: by alexgff – 14.12.16
FBTH: by TIV.NET – 14.11.23
Reviews and Rating - Google My Business: by Noah Hearle
Design Extreme – 3.42

Google Listings and Ads: by WooCommerce – 1.10.0
Intercom for WordPress: by Simon Blackbourn – 1.1
JT Comment Form: by Pavlo Opanasenko
Stas Mazur – 0.1

JT Complexity Levels: by Pavlo Opanasenko – 0.1
JT Design Collections: by Pavlo Opanasenko – 2.1
JT Roles: by Stanislav Mazur – 0.1
JT Success Stories: by Pavlo Opanasenko – 0.1
Meks Easy Photo Feed Widget: by Meks – 1.2.3
Members: by MemberPress – 2.2.0
Redis Object Cache: by Till Krüss – 2.0.22
SearchWP Related: by SearchWP – 1.4.6
SearchWP WooCommerce Integration: by SearchWP – 1.3.10
SearchWP: by SearchWP – 4.1.22
Simple Page Ordering: by Jake Goldman
10up – 2.3.4

YIKES Simple Taxonomy Ordering: by YIKES
Inc. – 1.2.7

SpeedGuard: by Sabrina Zeidan – 1.8.5
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.1
TIVWP Email (JT Version - do not upgrade!): by TIV.NET – 99.99.99
TIVWP Foundation: by TIV.NET – 14.02.03
TIVWP Google Analytics: by TIV.NET – 13.08.08
TIVWP Options: by TIV.NET – 13.07.29
TIVWP Redirect: by alexgff – 14.12.02
TIVWP Service Pages: by TIV.NET – 13.10.28
TIVWP Settings: by TIV.NET – 13.08.08
TIVWP Sidebars: by TIV.NET – 13.12.17
TIVWP Social Metas: by TIV.NET – 15.02.04
TIVWP XML Sitemap: by TIV.NET
Stanislav Mazur – 13.10.09

User Switching: by John Blackbourn & contributors – 1.5.8
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Stripe ACH Gateway: by Stanislav Mazur – 0.0.1
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.12.1
WooCommerce - Product Vendor: by Matt Gates – 91.4.8
WooCommerce: by Automattic – 6.1.0
WordPress Importer: by wordpressdotorg – 0.7
WordPress Social Login: by Miled – 3.0.5

### Dropin Plugins (2) ###

db-error.php: db-error.php
object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (7) ###

active-config.php: by  –
debug.php: by  –
Disable REST API: by  –
expose.php: by  –
jt-secure.php: by  –
log-wp-mail.php: by  –
sunrise.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: TIVWP WooCommerce One
Version: 13.10.14
Author URL: http://www.tiv.net/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: tivwp-wc-one/woocommerce/archive-product.php
tivwp-wc-one/woocommerce/cart/cart-shipping.php
tivwp-wc-one/woocommerce/checkout/form-billing.php
tivwp-wc-one/woocommerce/checkout/form-checkout.php
tivwp-wc-one/woocommerce/checkout/form-pay.php
tivwp-wc-one/woocommerce/checkout/form-shipping.php
tivwp-wc-one/woocommerce/checkout/payment-method.php
tivwp-wc-one/woocommerce/checkout/payment.php
tivwp-wc-one/woocommerce/checkout/review-order.php
tivwp-wc-one/woocommerce/checkout/thankyou.php
tivwp-wc-one/woocommerce/content-product.php
tivwp-wc-one/woocommerce/emails/email-downloads.php
tivwp-wc-one/woocommerce/emails/email-header.php
tivwp-wc-one/woocommerce/emails/email-order-details.php
tivwp-wc-one/woocommerce/emails/email-order-items.php
tivwp-wc-one/woocommerce/emails/email-styles.php
tivwp-wc-one/woocommerce/emails/plain/email-downloads.php
tivwp-wc-one/woocommerce/emails/plain/email-order-items.php
tivwp-wc-one/woocommerce/global/breadcrumb.php
tivwp-wc-one/woocommerce/loop/loop-end.php
tivwp-wc-one/woocommerce/loop/loop-start.php
tivwp-wc-one/woocommerce/loop/no-products-found.php
tivwp-wc-one/woocommerce/loop/orderby.php
tivwp-wc-one/woocommerce/loop/pagination.php
tivwp-wc-one/woocommerce/loop/result-count.php
tivwp-wc-one/woocommerce/loop/sale-flash.php
tivwp-wc-one/woocommerce/myaccount/dashboard.php
tivwp-wc-one/woocommerce/myaccount/form-edit-account.php
tivwp-wc-one/woocommerce/myaccount/form-edit-address.php
tivwp-wc-one/woocommerce/myaccount/my-account.php
tivwp-wc-one/woocommerce/myaccount/my-downloads.php
tivwp-wc-one/woocommerce/myaccount/my-orders.php
tivwp-wc-one/woocommerce/myaccount/view-order.php
tivwp-wc-one/woocommerce/notices/error.php
tivwp-wc-one/woocommerce/notices/notice.php
tivwp-wc-one/woocommerce/notices/success.php
tivwp-wc-one/woocommerce/order/order-details-item.php
tivwp-wc-one/woocommerce/order/order-details.php
tivwp-wc-one/woocommerce/single-product/product-attributes.php
tivwp-wc-one/woocommerce/single-product/review-meta.php
tivwp-wc-one/woocommerce/single-product/sale-flash.php
tivwp-wc-one/woocommerce/single-product/tabs/description.php
tivwp-wc-one/woocommerce/single-product-reviews.php
tivwp-wc-one/single-product.php


### Action Scheduler ###

Complete: 165
Oldest: 2022-01-14 03:14:46 -0500
Newest: 2022-01-20 03:47:01 -0500

Failed: 448
Oldest: 2020-10-19 05:14:34 -0400
Newest: 2021-11-29 06:09:07 -0500

Pending: 8
Oldest: 2022-01-20 03:56:31 -0500
Newest: 2022-01-25 03:00:56 -0500


### Status report information ###

Generated at: 2022-01-20 03:56:32 -05:00
```

</details>

**Comment by mikkamp** [comment]
From initial testing I was able to see a difference on frontend requests from 180ms > 360ms after activating the plugin.

There is very little we do on the frontend such as:
- Add a code to the header for site verification
- Google tracking snippet

Based on that I think we should be stricter on what part of the plugin gets loaded on the frontend. We have some of it load conditionally based on `is_admin` or whether it's a REST API request. However I think we should do some further investigation into what else can be limited.

**Comment by jorgemd24** [comment]
After doing some investigation I could narrow down the problem. I used Qcachegrind & xDebug to get the following reports.

Results from cachegrind with the plugin disable:

![image](https://user-images.githubusercontent.com/2488994/153480336-bdcd8f61-948c-45e8-bcc3-66baa3789db7.png)

Results with the plugin enable:

![image](https://user-images.githubusercontent.com/2488994/153480702-add21840-2a9f-4849-b9e9-ddd669af10ce.png)

The issue is related to protobuf, (protocol buffers) that is used to serialize structured data in the Google Ads Library. 
With the current implementation, we are calling the serialization data on every request, adding more than 200ms for each request.

There are some discussions about this on the internet: 

1. [Why is ProtoBuf so slow on the 1st call but very fast inside loops?](https://stackoverflow.com/questions/13735248/why-is-protobuf-so-slow-on-the-1st-call-but-very-fast-inside-loops)
2. [Suggestions for faster deserialization using Protocol Buffers](https://stackoverflow.com/questions/47902201/suggestions-for-faster-deserialization-using-protocol-buffers)

 When a request is received, the following steps are executed:

1. The CoreServiceProvider.php is registering: `ReviewAfterClicksNote` & `ReviewAfterConversionsNote` and its constructors are using a  `MerchantMetrics` object.
2. The `MerchantMetrics` object has a dependency on `GoogleAdsClient`.
3. The constructor `GoogleAdsClient` is calling `GoogleAdsFailures::init();`
4. `GoogleAdsFailures::init();` is executed and it calls the protobuf functions.
5. Adding between 200ms to 500ms to the total response. 

In some cases, this could be mitigated by:

```
        use GrpcSupportTrait;	

         ……
	
        // Initializes preemptively the GoogleAdsFailures type when
        // gRPC is not available.
        if (!self::getGrpcDependencyStatus()) {
            GoogleAdsFailures::init();
        }


```
See: https://github.com/googleads/google-ads-php/blob/9be8c723ce1edf55f6fd7df8383ad4cbecb93079/src/Google/Ads/GoogleAds/Lib/V6/GoogleAdsClient.php#L55

**Next Steps:**

- Call `GoogleAdsFailures::init()` only when it is necessary.
- Reduce the number of services & classes depending on the request type: admin, ajax or visitor.

**Comment by mikkamp** [comment]
The amount of ms it's adding is going to be relative to the speed of your system and whether it's been served from a virtual container (which can be the case with docker on MacOS).

Since you referred to the Notes in particular I was wondering if we can change the NoteInitializer a bit. We added a scheduled action to ensure these notes are only checked once a day. But we pass an array of notes to the initializer (which will trigger the constructor of each note class). Can we make the initializer container aware and have it load the instances only when the cron schedule is triggered. Also worth noting that [this](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Notes/NoteInitializer.php#L55) validation doesn't really add much since we specifically ask the container for only the classes with interface Note.

Another thing I was thinking of was the [maybe_register_services](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L113) function. We get all Services and then check if they are Registerable, that list is reused to check if they are also Activateable or Deactivateable. We don't have any Activateable or Deactivateable services that are not Registerable, so maybe we can win a bit by only retrieving Registerable there. Or if that's not a good idea maybe we should be stricter on what inherits from Service, for example it doesn't look like Note needs to be a Service.

**Comment by jorgemd24** [comment]
>The amount of ms it's adding is going to be relative to the speed of your system and whether it's been served from a virtual container (which can be the case with docker on MacOS).

Yes, it is relative to the host, what I wanted to communicate was that the difference between running or not `GoogleAdsFailures::init()` could be significant. 

>Since you referred to the Notes in particular I was wondering if we can change the NoteInitializer a bit. We added a scheduled action to ensure these notes are only checked once a day. But we pass an array of notes to the initializer (which will trigger the constructor of each note class). Can we make the initializer container aware and have it load the instances only when the cron schedule is triggered. Also worth noting that this validation doesn't really add much since we specifically ask the container for only the classes with interface Note.

Thanks for this suggestion, we could load the instances in the add_notes function so it will be only called when the cron schedule is triggered. For this, we need to update the NoteInitializer constructor into ActionSchedulerInterface & ContainerInterface and then we can use the container to load the instances in the add_notes function. 

The Service interface could be removed from the Notes interface as Notes are not required to be loaded until the add_notes function is invoked.

> Another thing I was thinking of was the [maybe_register_services](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L113) function. We get all Services and then check if they are Registerable, that list is reused to check if they are also Activateable or Deactivateable. We don't have any Activateable or Deactivateable services that are not Registerable, so maybe we can win a bit by only retrieving Registerable there. 

Do you mean to update $services = $this->container->get( Service::class ); into $services = $this->container->get( Registerable::class ); ?

**Comment by mikkamp** [comment]
> we need to update the NoteInitializer constructor into ActionSchedulerInterface & ContainerInterface

We have a mix of how we handle this in various classes. But if the container is not needed in the constructor then the class can implement the ContainerAwareInterface and use the trait ContainerAwareTrait.

> Do you mean to update $services = $this->container->get( Service::class ); into $services = $this->container->get( Registerable::class );

Yes that's exactly what I meant. If I search for `implements.*Service` I find 66 results, but `implements.*Registerable` finds 36 results. So it would initialize a lot less classes, although some of those might still get initialized by passing them in a constructor. But I think it's at least worth exploring if this might have any effect.

**Comment by jorgemd24** [comment]
>We have a mix of how we handle this in various classes. But if the container is not needed in the constructor then the class can implement the ContainerAwareInterface and use the trait ContainerAwareTrait.

Thanks, I used  ContainerAwareTrait to load the instances. I created PR #1244.

> Yes that's exactly what I meant. If I search for implements.*Service I find 66 results, but implements.*Registerable finds 36 results. So it would initialize a lot less classes, although some of those might still get initialized by passing them in a constructor. But I think it's at least worth exploring if this might have any effect.

I tried updating it to `$services = $this->container->get( Registerable::class );` however the Registerable:class needs to be added to at least two providers CoreServiceProvider and JobServiceProvider to make the plugin work. I think at the end it will load a similar number of instances and I do not see any significant change in the performance.

**Comment by mikkamp** [comment]
I'm not sure I follow why those two providers would need to be Registerable. They extend the [AbstractServiceProvider class](https://container.thephpleague.com/3.x/service-providers/) so we don't need to call it's register function explicitly. If there isn't a significant performance change then it's probably best to leave it as is anyway.

I'll take a closer look at the PR since that looks like it's a major improvement.

**Comment by jorgemd24** [comment]
As far as I understand the `Registerable interface` needs to be added in the `provides array` of at least one of the providers so it can load the definitions related to that alias. Otherwise, it is throwing `Registerable is not being managed by the container or delegates` because the container does not have any definition yet with the tag "Registerable".

If I add the Registerable interface to the `provide array` of CoreServiceProvider it will throw: 

```
Automattic\WooCommerce\GoogleListingsAndAds\Notes\NoteInitializer::__construct() must be an instance of Automattic\WooCommerce\GoogleListingsAndAds\ActionScheduler\ActionSchedulerInterface, string given
in /var/www/html/wp-content/plugins/google-listings-and-ads/src/Notes/NoteInitializer.php on line 51
```

That's because the definition of ActionScheduler is defined in JobServiceProvider. That's why I think the Registerable interface needs to be added at least in those two providers. This could have other side effects that are not visible yet therefore I agree with you:

>If there isn't a significant performance change then it's probably best to leave it as is anyway.
