### ISSUE TITLE
Conflict with Woocommerce v 6.2.1 leads content API to send incorrect URL

### ISSUE THREAD

**Issue by d-voorhees** [woocommerce/google-listings-and-ads#1276]
Woocommerce and WPEngine support helped diagnose and pinpoint this issue, which we have solved for now by reverting to Woo 6.2.

With the update to Woocommerce 6.2.1, the Content API has begun submitting the incorrect product and image URLs to Google Merchant, resulting in Google Merchant removing our products from their listings. This morning we were notified 66 listings had been removed from Google Merchant due to them having the wrong domain URLs. The URLs that were being sent from the Content API were links to our staging site (a url not registered with Google Merchant), not our live site. Source code investigation on our live site revealed there were no links in our source code that point to the staging site, that could lead to staging URLs being sent to Google Merchant.

Not sure exactly how or why this is happening in the plugin code, but as I said rolling back Woocommerce to the previous version fixed it for us for now. Attached are screenshots of our merchant dashboard once we rolled back and manually resent the product data to Google Merchant; you can see we are now back to having all our products active again.

<img width="804" alt="Google merchant once we rolled back to Woocommerce 6 2" src="https://user-images.githubusercontent.com/9328008/155798396-6cc107f3-690c-4e8d-8ebb-3efae045ab94.png">

Thanks, if there's any other clarifying information that would help you pinpoint the issue more please let me know. I know vague bug reports can be hard to wrangle sometimes.

**Comment by findingsimple** [comment]
Hi!

> With the update to Woocommerce 6.2.1.....This morning we were notified 66 listings had been removed from Google Merchant due to them having the wrong domain URLs. The URLs that were being sent from the Content API were links to our staging site

At face value that doesn't make a lot of sense that your site would have started using a staging URL (not sure how your live site would know about a staging site/url).

By any chance, did you test the 6.2.1 update on a separate staging site with all the same connection details as your live site and in doing so submit staging data to your live merchant center account? Or alternatively, has some data from your staging site been copied across to your live site as part of migrating testing data

I believe you have a support tick in process. Could you please continue discussing the issue with our support team. Once we get to the bottom of the cause if its dev related we can create an issue or continue this here.

**Comment by melek** [comment]
We've had a recurrence of this issue, also on WP Engine, where a user had about one third of their GMC catalog overwritten with the staging site URL. To resolve the issue they deleted the products in Google, then disconnected/reconnected their Google account on the live site. They reported this worked, but they then had to reconfigure their shipping information in Google (not sure why). 34710573-hc

@jconroy They have responses to the questions you asked the original poster: 

> By any chance, did you test the 6.2.1 update on a separate staging site with all the same connection details as your live site and in doing so submit staging data to your live merchant center account? 

The user says this is exactly what they did; They copied the live site to staging (a 1:1 copy) with WP Engine's tools and tested the update to 6.2.1 - also around the time of this issue, a month+ ago.

Since that happened, they say that about a third of their catalog had been replaced. The majority of their products undergo no changes month to month, not sure if that matters.

> alternatively, has some data from your staging site been copied across to your live site as part of migrating testing data

No, the user only ever copies the live to staging, not the other way around.

I'm mostly commenting here to help surface a solution to others who might be experiencing this problem. The shop owner is going to watch this issue in case it progresses but doesn't have an ongoing ticket, so I'm unsure if we should reopen this issue or not at this time.

**Comment by mikkamp** [comment]
If the site is copied to a staging site, all the connection settings are also copied over. Unless this is done during the initial sync, it generally won't start automatically syncing all the products as soon as the staging site is created. However since the staging site is also considered as "connected" there are plenty of events that could trigger products to be synced:

- Products have been submitted more than 25 days ago (could trigger a scheduled sync on both the live site and staging site)
- Products are updated on the staging site
- A product update event is triggered by another plugin while changing some of the details

There are plenty of other events that could trigger a product to be removed from the catalog, such as an item goes out of stock, or a staging product becomes a draft or is trashed. This wouldn't trigger staging URL's to be submitted but this could still cause unexpected behaviour of products being removed from the catalog.

Since we use a specific `site_url` for verification (not stored locally), we should be able to add an additional check to only sync when the `site_url` is still the same as the one we used for verification. I'm going to log a separate issue for this.
