### ISSUE TITLE
Support both [unit_pricing_measure] and [unit_pricing_base_measure]

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/google-listings-and-ads#1337]
## User story

If you sell a product based on measurements they seem to get rejected as the extension doesn't support [unit_pricing_measure] and [unit_pricing_base_measure]. At least from 4868841-zen.

### Is your feature request related to a problem? 

Yes, it should support the [unit_pricing_measure] and [unit_pricing_base_measure] properties. Otherwise this extension is of no use.

#### How to reproduce the problem
Use an extension like Measurement Price Calculator and see if it then works in Google Listings & Ads.

### Describe the solution you'd like 
If you use an extension to add units of measure to a product, you shoudl then be able to use our Google Listings & Ads extension and not get rejected since it doesn't suport [unit_pricing_measure] and [unit_pricing_base_measure]

### Describe alternatives you've considered 
Our Google Product Feed extension supports these two properties, we should support this in this extension as well for anyone whos products use a unit of measurement.

**Comment by findingsimple** [comment]
Thanks @ryanr14 can you add as a feature request to the ideas board please and link here

**Comment by ryanr14** [comment]
I added it here, but there wasn't a specific Google Listings & Ads plugin.

https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/44951842-support-both-unit-pricing-measure-and-unit-pric

**Comment by XcitingWebdesign** [comment]
Hi @jconroy, hi @puntope !
The ideas forum seems to be deprecated now. I've updated this post: https://wordpress.org/support/topic/unit-pricing-measure-2/#post-17133102

I've also submitted a feature request on WooCommerce.com, but it isn't approved as of now.

The original poster seems to have opened this issue because the plugin can't be used for all bulk-related stores in Germany or Austria - the third biggest economy in the world.

The "easy" fix would be to make those two attributes selectable in the "Attribute Matching" tab. Both WooCommerce Germanized and WooCommerce German Market create custom global variables for [unit_pricing_measure] and [unit_pricing_base_measure] - we just have to be able to match them. :-)

Best,
Franz

PS: This issue is marked as closed, but with the ideas link 404'ing I'd like you to consider re-opening this.
