### ISSUE TITLE
Enhancement - TreeSelectComponent should clear the previous search when an option is selected.

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#1489]
### Describe the enhancement:
When I am looking for an option in the TreeSelectComponent, I am expecting that once one option is selected, the search should be clear so I can search for another item without deleting the previous search manually.  

### Steps to reproduce:

1. Go to Edit Free listings -> Update the Audience country
2. Search for any country, select the country, for example Italy
3. Search for another country, here it is needed to delete Italy manually and then search for the new country.

https://user-images.githubusercontent.com/2488994/167125778-55246232-63b2-4251-bd58-87bb672d04da.mp4

### Expected behaviour:
Once an option is selected, the previous search should be clear.

### Actual behaviour:
Once an option is selected, the previous search is still showing.

**Comment by puntope** [comment]
👁️  I was experimenting with this for a bit. Is true that the user should remove the filter but on the other side the user can feel consistency in the current tree after selecting the option. 

For example, if we remove the filter means the tree will go back again to the unfiltered state hidden the options highlighted by the filter.

See video with the feature implemented:

https://user-images.githubusercontent.com/5908855/171199314-b1dba5e1-31d9-40e2-b6e3-ade764ab72a6.mov

Video without the feature:

https://user-images.githubusercontent.com/5908855/171199613-e4b7da7f-8a99-4748-926d-9759058c476c.mov

So, Im not sure whats better in terms of UX.

**Comment by puntope** [comment]
@j111q 

Maybe could you suggest any of the two solutions?

https://github.com/woocommerce/google-listings-and-ads/issues/1489#issuecomment-1142219631

**Comment by j111q** [comment]
👋 Hi all, thanks for flagging and showing the issue so clearly. @shivanarrthine and I discussed this today and our preference is:

1. Can we keep the selected item in focus, AND remove the search term? Similar to how [Ant Design system does it here](https://ant.design/components/tree-select/), or here's a screencap:
![Screen Capture on 2022-06-09 at 12-09-57](https://user-images.githubusercontent.com/65582817/172762907-f7f89f77-94b1-4726-a51e-e958535217ac.gif)

2. If the above suggestion ☝️  isn't possible, then we would prefer your first solution above, where the search term is removed and the selected item doesn't stay in focus. The reason is because it's troublesome for users to have to erase their search terms manually, especially if they're choosing many items. 

Let us know what you think! 🙏

**Comment by puntope** [comment]
> 1. Ant Design system does it here

Notice this is because is expanded already. Otherwise is not persisting.


https://user-images.githubusercontent.com/5908855/172816269-37db7b3c-6786-434c-b62b-cf61fab78939.mov

I will implement for now the solution 1, removing the filter.

**Comment by jorgemd24** [comment]
Thanks, @j111q for your input on this! 💯 

@puntope, I think that would be fine, ideally, the tree should be expanded so we could keep consistency between the search term, the tag and the tree however if this would require a big effort I think option 1 should be ok. From my point of view, it did not feel good that every time the user would like to search had to go to the selector, delete the search term and type again.
