### ISSUE TITLE
Valid product image URLs not being detected in Google Merchant Center

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1582]
### Describe the bug:

Several users are reporting their products not syncing due to invalid image URLs error. GMC is unable to detect product images on some sites and return the following errors:

`[imageLink] This value is not a valid URL.`

`[additionalImageLinks[0]] This value is not a valid URL.`

There's been a number of support requests related to this issue all of which we've not been able to identify the cause.

### Steps to reproduce:

There's no specific steps to reproduce this issue as it appears to happen randomly.

### Additional details:

This issue was discussed in p1654635110739929-slack-C01E9LB4X61

### Support requests

5338712-zen, 5263382-zen, 5203580-zen, 5208482-zen Forum 1, 4915339-zen, 4821349-zen

**Comment by findingsimple** [comment]
> This issue was discussed in p1654635110739929-slack-C01E9LB4X61

@sukafia What was the outcome of the conflict testing suggested in the slack thread discussion? What problem solving has been done?

There is no additional information for us to work with.

**Comment by findingsimple** [comment]
@mikkamp can you please dive into these tickets for the HEs?

**Comment by sukafia** [comment]
> > This issue was discussed in p1654635110739929-slack-C01E9LB4X61
> 
> @sukafia What was the outcome of the conflict testing suggested in the slack thread discussion? What problem solving has been done?

I recommended a conflict test in the recent support request (5338712-zen), I'm still waiting for an update. However, I imagine narrowing this down with a conflict test is going to be difficult, since it takes some time for product updates to reflect in GMC. 

Meanwhile, I see I didn't link to the [forum thread](https://wordpress.org/support/topic/this-value-is-not-a-valid-url-additionalimagelinks0/) I added to the issue.

**Comment by mikkamp** [comment]
I was able to reproduce one error where the name of the image is `El-viaje-Fantástico-del-Osito-Gominola-Mockup.jpg` (note the accented `á`). If I try to sync with that image name I get the same error:

```
[imageLink] This value is not a valid URL.
```

That's something that we can look at fixing, although I'm not certain that is the case in all the linked support requests.

**Comment by mikkamp** [comment]
As mentioned in the PR, the fix would only resolve the validation error for sites that are actually using accented characters in the image URL's. I could find 3 sites linked in this issue with this problem, but there are several linked issues which appear to be using images with normal characters.
I've tried to track down additional patterns / reasons why the images might not be validated, but couldn't find any other reasons. I'd like to get this fix included in a release first. If after that we still find cases where image URL's aren't validated then we can reopen this issue. It would be helpful if we can get some details on specific image URL's which are not validated.

**Comment by sukafia** [comment]
We're seeing new reports of this issue. Some of the users confirmed renaming the images on their computers, removing non-English characters and re-uploading them resolved the issue. A user confirmed it was caused by having Chinese characters in the image file name. 

After assisting a couple of users with the issue, I'm confident it's caused by having special/non-English characters in the image file names. (3 of the sites in the ticket are non-English sites)

5682476-zd-woothemes
5688120-zd-woothemes
5744306-zd-woothemes
5760681-zd-woothemes
5756988-zd-woothemes

**Comment by puntope** [comment]
What about using https://www.php.net/manual/en/function.urlencode.php

**Comment by puntope** [comment]
Btw, How do you add images with wrong characters? I see WP fixing that when I upload the image

**Comment by puntope** [comment]
After further investigation I see the next:

- Adding a product image as ñññ.png was successfully sent to google. Also google validated the URL properly ✅ 
- Adding a product image as æą€€.png was successfully blocked by the validator, so product wasn't sent to Google and the proper notice was added to the product. ✅ 
- For other unknown cases with invalid URL that pass the validator but are not validated by Google, we offer information in product Issues section. ✅ 

@sukafia  Could you clarify whats exactly the expected behaviour for the issue?

**Comment by mikkamp** [comment]
@puntope I was looking at the [docs here](https://support.google.com/merchants/answer/6324350?hl=en). It mentions it supports only ASCII characters for the URL, but obviously some other characters work. I wonder though if we go with your original suggestion to use url_encode or something similar.

So an image of `æą€€.png` would become `%C3%A6%C4%85%E2%82%AC%E2%82%AC.png`.
Would that allow Google to validate the URL? Also would the webserver still interpret the link correctly and return the correct image?

**Comment by sukafia** [comment]
> Btw, How do you add images with wrong characters? I see WP fixing that when I upload the image

Perhaps it doesn't in all cases. I'm not familiar with the exact characters that causes the error but a user confirmed in their case it was Chinese characters and that renaming the images on their computer and re-uploading resolved the issue. I also investigated a US site where I felt special characters were the culprit. Here's what I found when I checked their image titles:

![lXojOB.png](https://user-images.githubusercontent.com/60121732/206423708-9505a3d1-4853-4fbd-a249-f7d8ac713870.png)

![Tunr5V.png](https://user-images.githubusercontent.com/60121732/206423764-9bf00aca-0d31-4358-85bf-3e33f120c6e9.png)

Renaming the images and reuploading resolved the issue. (I don't remember if those were all the images on the product page as one image on the product page triggers the error for that product)

If it'll help, there's an open ticket with a similar issue: 5760681-zd-woothemes. I viewed the source codes and noticed the image URLs look like this:

- https://i0.wp.com/hey-hey.eu/wp-content/uploads/2020/07/cropped-insta-scaled-1.jpg?fit=32%2C32&#038;ssl=1
- https://i0.wp.com/hey-hey.eu/wp-content/uploads/2020/07/cropped-insta-scaled-1.jpg?fit=32%2C32&ssl=1
- https:\/\/hey-hey.eu\/wp-content\/uploads\/2021\/10\/hey-hey-butcher-jacket-1-scaled.jpg&quot;,&quot;alt&quot;:&quot;&quot;,&quot;src&quot;:&quot

(Notice the special characters from Jetpack CDN? I'm not sure if it's related or if Google is fetching that entire URL. Initially, when I flagged this issue I suspected it could be related to CDNs but we rolled it out. FYI, Jetpack is installed on all the affected sites.)

**Comment by mikkamp** [comment]
Thanks for the additional details, although I haven't found any reproducible scenarios from those tickets.

For example we only extract the image URL from the product, your screenshot shows that this was: `https://vernte.com/wp-content/uploads/2022/06/Untitled-10-x-10-in-13.png`. We don't look at the title at all. The only thought that comes to mind is maybe it's a case sensitive issue where the file is called `untitled-10-x-10-in-13.png`, or possibly one of the dashes is a different character (although I'd find that strange since they are all auto replacements).

The following error message is one that comes directly from the [validation rules in the plugin](https://github.com/woocommerce/google-listings-and-ads/blob/2.3.2/src/Product/WCProductAdapter.php#L763-L774):
> [imageLink] This value is not a valid URL.

This prevents the product from being synced to Google. Since we use a library for that validation (plus a normalizer) I suspect on some hosting platforms this doesn't run correctly (which makes the validation failures hard to reproduce). I tested locally and I can upload a product with the image name `https://vernte.com/wp-content/uploads/2022/06/Untitled-10-x-10-in-13.png` it passes validation checks and syncs to Google.

As for the links `https://i0.wp.com/hey-hey.eu/wp-content/uploads/2020/07/cropped-insta-scaled-1.jpg?fit=32%2C32&#038;ssl=1`
Those extra parts in the URL are not a problem and image links like this pass validation (I tested this locally), however it's a resized image of 32x32 pixels. So that might still fail when synced to Google (but we'd expect a different error message then).

**Comment by mikkamp** [comment]
Just to confirm I setup a new atomic site with Jetpack, both with and without the image optimizer enabled it has no problems syncing the images to Google.

![image](https://user-images.githubusercontent.com/11388669/206503821-e2565072-acf3-49b1-a8bf-6933c9750fe4.png)

I'd imagine there is something hosting/platform specific going on with the sites that don't work. But we'll need access to one of those environments to be able to troubleshoot further.

**Comment by sukafia** [comment]
New reports in 5781235-zen and 5782432-zen

**Comment by mikkamp** [comment]
Thanks for the report, the first site doesn't mention any specific products, I checked a few random products on the frontend and they seemed to be regular ascii characters.

For the second site I found an image name like `Untitled-1000-×-1000-px-7-2.png` the character in the middle isn't a regular `x`. I think we can do some testing with that image name to see if we can find a way around it. Until then the easiest work around is to rename those images as you suggested in the tickets.

**Comment by mikkamp** [comment]
I did some more testing for these image names, but unfortunately the Google image scraper doesn't accept url encoded names.

### Steps to reproduce an image with an invalid name
1. Create a png image with the name `Untitled-1000-×-1000-px-7-2.png` and upload it to a publicly accessible folder on your site (I placed it in wp-content/uploads).
2. Create a csv file to update the image name using the importer (replace the product ID and the image URL in the following example):
```csv
ID,Type,Images
1234,simple,https://domain.test/wp-content/uploads/Untitled-1000-×-1000-px-7-2.png
```
3. Go to Products > Import and use the created CSV file to update the product (make sure to check update product).
![image](https://user-images.githubusercontent.com/11388669/207548448-bc905948-1e4c-4197-b1c5-d91ce51563d2.png)
4. Go to the connection test page `wp-admin/admin.php?page=connection-test-admin-page` and sync the product ID (or wait till the scheduled sync completes.
5. Confirm that there is an error syncing the product because the image is not a valid URL.

### URL encode image names
I created the branch https://github.com/woocommerce/google-listings-and-ads/tree/fix/1582-urlencode-image-names to url encode the names. This works for syncing the product to the Google Merchant Center, the image link is accepted and does still load when I click on the link.
![image](https://user-images.githubusercontent.com/11388669/207549033-3f0f730f-075b-4f83-9e00-028c4ed3ef13.png)

However after a while Google will crawl the image, and this is the point where it fails.
![image](https://user-images.githubusercontent.com/11388669/207549892-9f184f0f-1b96-478b-b515-6ea807515604.png)
The learn more links to the article: https://support.google.com/merchants/answer/6183365?hl=en

So unfortunately we can't allow images with characters that aren't allowed in the URL. What we can do as a follow up here is make the error message clearer. Going from:

```
[imageLink] This value is not a valid URL.
[additionalImageLinks[0]] This value is not a valid URL.
```

To:
```
Product image "Untitled-1000-×-1000-px-7-2.png" is not a valid name [image]
Product image "æą€€.png" is not a valid name [galleryImage]
```

That in combination with a FAQ in the docs explaining how to correct image names should make it easier to help resolve the errors.

**Comment by mikkamp** [comment]
> That in combination with a FAQ in the docs explaining how to correct image names should make it easier to help resolve the errors.

@sukafia The changes to improve the error messages have been merged and will be added to the next release. Can we follow up with some instructions on how to rename images in a FAQ. Similar to the info you have in the ticket, but just a public version so users can be pointed to it, if they have problems with their image names.

**Comment by johndcoy** [comment]
@mikkamp looking back at 5760681-zd-woothemes, while renaming with the use of an underscore in the file name, did not fix the issue. They have Lazy Loading enabled so I disabled it and reuploaded a new image with ASCII/Latin characters only - no special characters and I'm currently waiting for an update.

However, I also see that they have an error mentioned in earlier logs that don't appear in recent ones:

```
filter_valid_statuses A Google ID was not found in Merchant Center.
```

Any insight on this error and if it has any bearing on the image issue?

I also noticed we do not have public-facing docs for recommendations yet, likely since the suggestion did not work for 5760681-zd-woothemes

**Comment by mikkamp** [comment]
Thanks for taking a look @johndcoy 
I had a closer look at that ticket, it doesn't seem like the image names are still a problem. I left a reply in the ticket as it looks like not every destination country has a matching shipping rate setup.

**Comment by mikkamp** [comment]
> Can we follow up with some instructions on how to rename images in a FAQ. Similar to the info you have in the ticket, but just a public version so users can be pointed to it, if they have problems with their image names.

@darcie Would you be able to help get some instructions on how to rename images if they aren't using regular "ASCII/Latin characters" added to the docs/FAQ?

**Comment by darcie** [comment]
Thanks for the ping, @mikkamp. I'll add that to [our FAQ page](https://woocommerce.com/document/google-listings-and-ads-faqs/).

**Comment by darcie** [comment]
Updated: https://woocommerce.com/document/google-listings-and-ads-faqs/#section-11
Thanks to @johndcoy for adding the new section!

**Comment by johndcoy** [comment]
Sure thing @darcie ! I needed it for a site using Hebrew characters so I mocked something up. I'm sure you could write it better so feel free to make changes.

**Comment by mikkamp** [comment]
Thanks to both of you for getting that added to the documentation. Hopefully in combination with the improved error message it will help merchants better understand how to correct the error without needing direct support.
