### ISSUE TITLE
Remove the identiier_exist logic entirely

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1592]
### Background

Every year Google comes out with [new changes to the product feed spec](https://support.google.com/merchants/answer/11905642). 

The one that is most applicable to Woo merchants using the plugin is updated guidance for unique product identifiers. 

Generally speaking, Woo merchants should fill out the identifiers if they can to get the most out of shopping ads + free listings. Previously, if there was a missing GTIN and our systems identified this, it would lead to a disapproval of the offer. 

Now it leads to a demotion only, which means the product can serve but may not get as many clicks/impressions.

### Describe the bug:

Despite this new product update, the issue is... there will still be scenarios where there this [disapproval](https://support.google.com/merchants/answer/9464748?hl=en) appears because of the logic of how identifier_exist = false is implemented. 

Essentially, identifier_exist = false occurs when a merchant doesn't update any identifiers within the product editor. 

This is then sent to MC.

The Google team have advised that we should **remove the identiier_exist logic entirely in GLA**. 

This means the `identifier_exist` property won’t be submitted to Google. 

They have confirmed that there shouldn't be any issues with removing identifier_exists. 

Products that lack unique identifiers should still serve just in a demoted state as opposed to being disapproved for identifier exists misuse item error.

So to clarify - `identifier_exist` should not be set to either true or false. The property should be removed completely.

This is aimed at addresses issues like "Incorrect value: identifier exists [identifier_exists]"  [reference](https://support.google.com/merchants/answer/9464748?hl=en)

### Expected behavior:
The `identifier_exist` property is never set or sent to Google

### Actual behavior:
Currently, we set `identifier_exist` to false by default. If an identifier is set e.g. "GTIN" the we set `identifier_exist` to true.

**Comment by andywestley** [comment]
Hi, I understand this issue is closed, but I wonder if I can ask a question. My Woocommerce website currently sells items I craft or print myself - over 500 including size variations. I've set up the product feed but Google is penalising me because I don't supply an identifier. But I can't as my products don't have one. I've just managed to track down that supplying "identifier_exists: false" by default used to be a feature and that this change removed it. But perhaps the change should have been to stop setting it by default? For sellers reselling manufactured items I can see that setting it to false by default could be misleading, but to have no way to set it in a genuine case is tricky. The only solution for me is to setting every one of the 500+ products manually in Merchant Centre. It would be great I could set a global feed attribute in the way I've had to for Brand Name.

**Comment by Brianmitchtay** [comment]
Similar to the above, seeing an issue with a case of a merchant (5945896-zen) who sells thousands of different items which are all vintage and don't need identifiers. After having this value removed from GL&A it appears that their only way to enable their products to be listed is to individually mark each one of them as not requiring an identifier. 

It seems that it would be ideal if there were a way to add a global attribute that intentionally sets `false` for the `Identifier_exist` value.

Notably, their experience makes me believe that the [FAQ in the docs about this](https://woocommerce.com/document/google-listings-and-ads/faqs/#section-11) is incorrect, and that simply leaving the field blank is not the same as marking the `identifier_exist` as false.

@jconroy Would you like me to open a new issue for this? Have I misunderstood something about this situation?

**Comment by MatthiasReinholz** [comment]
Hi @andywestley and @Brianmitchtay,

let me help you with this case.
You're right that the FAQ is outdated, I'm going to work on that today.

`identifier_exists` is an attribute that does not exist anymore. Therefore, you should never try to send it. Setting it to `false` will result in errors.

The underlying issue is that Google always needs a unique ID for each product in the catalog. If you don't have `GTINs`, the recommended solution is to send values for both attributes `brand` and `MPN`.

@andywestley in your case, you don't have `GTINs` but you may still utilize internal identifiers for your products. Within WooCommerce, you are most likely using unique `SKUs` for each product and variation.

An effective way to resolve your issue would be to use the attributes mapping tool of Google Listings & Ads:
- Go to **Marketing > Google Listings & Ads > Attributes**
- Click `Create attribute rule`
- Select `MPN` as the target attribute
- Assign the value from an existing product field and select `SKU` as the option

Important: if you're using the `MPN` and don't send `GTINs`, you'll also have to set a value for the `brand` attribute. You can repeat the steps above to set an attribute mapping rule for the `brand` attribute. If you're selling custom items under your store's name, you may assign your store's name as a fixed value.

Let me know if you have any further questions!

**Comment by andywestley** [comment]
https://support.google.com/merchants/answer/6324478?hl=en-GB

Suggests that the property exists and a false value is valid.

Google is certainly penalising me without an identifier. I used the
approach you suggested above to set a global "brand" value, but that wasn't
enough. As soon as I used the merchant center front end and markled all the
products as being handmade or unique, google started to include products in
free listings.

I'll set up an attribute rule to use my SKU, but I'm still not convinced.

Andy

**Comment by MatthiasReinholz** [comment]
@andywestley the help center article you shared seems to be outdated. Thanks for bringing this to my attention. I just reported it to Google.
I'm sorry that there is still so much contradictory information available about this topic. We're actively working on resolving this.

What you're saying makes sense. If you send the `brand` attribute but no `MPN`, it won't work.
Sending `brand` plus `MPN` will do the trick.

**Comment by Brianmitchtay** [comment]
Hi @MatthiasReinholz and thanks very much for your reply, I'm passing that along to the merchant who inquired via ticket and I imagine they'll be pleased to hear it
