### ISSUE TITLE
Edit Free Listings: Navigate away prompt shows up when trying to go to non-React-powered pages

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1640]
### Describe the bug:

In Edit Free Listings, without making any changes, when we click on the top left back button, we can exit the page and go back to the dashboard. Since there is no unsaved data, there is no navigate away prompt. All good and expected.

However, if we don't click on the top left back button but instead we click on some non-React-powered pages like WordPress Dashboard menu item, the navigate away prompt will show up. 

Similar issue happens after we make some changes and click on "Save changes". Click on top left back button, no prompt; Click on WordPress Dasboard menu item, the prompt shows up.

I think this issue may be related to issue https://github.com/woocommerce/google-listings-and-ads/issues/1579 and its PR https://github.com/woocommerce/google-listings-and-ads/pull/1580. Tagging PR assignee @puntope and reviewer @tomalec here, in case you have some idea about this issue.

#### Reproducing the issue

This issue can be reproduced by using the `feature/shipping-integration-subdivisions` branch (at commit 45464d014ff4a5a863fa87275e97b89fbb41828c), with WooCommerce version 6.8.0 (tested by @ecgan) and WooCommerce version 6.9.0 (tested by @nima-karimi).

This is NOT reproducible with WooCommerce version 6.6.1 (tested by @ecgan).

📹 Demo video of the issue with my voice:

https://user-images.githubusercontent.com/417342/185403065-0df903ed-76ec-47f7-aac4-908304dccbd2.mov

### Steps to reproduce:

1. Use WC version 6.8 or 6.9.  
2. Go to Edit Free Listings.
3. Without making any changes, click on the WP Dashboard menu item. (Behavior A)
4. Make some changes and click on "Save changes". Wait for saving to be done.
5. Click on the WP Dashboard menu item. (Behavior B)

### Expected behavior:

Behavior A & B: there should be no prompt, and we should be able to go to the WP Dashboard page successfully.

### Actual behavior:

Behavior A & B: A prompt shows up, blocking our navigation.

**Comment by eason9487** [comment]
📝  Add related issues to be fixed together later

## Issue A: history v5 (WC 6.7) compatibility that `history.block()` has a different behavior.

Calling `history.block()` will continue to lock browser-level navigating events such as refresh or close the page. It's the same as the main content of this GH issue.

https://user-images.githubusercontent.com/17420811/189304415-cdd57be8-67f3-47b8-b8a1-dd92c90ce3dd.mp4

### Replication

1. Enter free listing editing page.
2. Refresh the page.

### Expected behavior

Should not be prompted when no changes.

## Issue B: history v5 (WC 6.7) compatibility that the passed-in `location.pathname` has different results on the leading backslash.

Since WC calls `history.push()` with a path that starts with `'admin.php?...'`, it brings the inconsistent `location.pathname` results. it leads to the comparison of the allowed locations mismatch.

https://user-images.githubusercontent.com/17420811/189304436-1cb3de91-23d4-447d-9c33-dfbfe9a80027.mp4

### Replication

1. Enter free listing editing page.
2. Change audience countries.
3. Click on step 2 title.

### Expected behavior

Should not be prompted when switching steps.

## Issue C: history v5 (WC 6.7) compatibility that the passed-in `location.pathname` has different results between `push` and `popstate` events

Similar to issue B, the different `location.pathname` results cause the mismatched comparison.

https://user-images.githubusercontent.com/17420811/189314917-45b843c1-be0f-4d2d-b0b6-f89d4b2be1fc.mp4

### Replication

1. Enter free listing editing page.
2. Change audience countries.
3. Click the Continue button.
4. Click the browser's previous page button.

### Expected behavior

Should not be prompted when switching steps by the browser's previous/next button.

## Issue D: history v5 (WC 6.7) compatibility that it needs to call `history.block()` again if stayed in the allowed locations after calling `unblock()`

https://user-images.githubusercontent.com/17420811/189314872-1bcbce43-5a8a-45b4-a7c5-96bd37c20011.mp4

### Replication

1. Enter free listing editing page.
2. Change audience countries.
3. Click on step 2 title and confirm the prompt to leave. (The prompt is not expected and belongs to issue B)
4. Click the "Google Listings & Ads" or "Overview" link on the admin menu.

### Expected behavior

Should be prompted when there are any unsaved change.

## Issue E: Comparing two country arrays with the same set may result in mismatched on the paid ads setup page

It's not a compatibility issue but a relevant bug.

https://user-images.githubusercontent.com/17420811/189304507-364337b1-4a59-4fda-8a7e-7bf8d3bcaba6.mp4

### Replication

1. Enter paid ads setup page and proceed with the paid campaign setup step.
2. Unselect and select all countries.
3. Click the "<" icon on the top left side of the page.

### Expected behavior

Should not be prompted when no changes.
