### ISSUE TITLE
GLA should not appear above the "Coupons" marketing sub menu item

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1729]
### Describe the bug:

GLA and other marketing extensions can appear above the "Coupons" marketing sub menu item in the WP dashboard

<img width="359" alt="Screen Shot 2022-10-14 at 6 15 21 pm" src="https://user-images.githubusercontent.com/355014/195793342-b5ba6ae4-4cdc-447c-bb69-de274c02fbda.png">

GLA and others "shouldn't be higher than Coupons"

peapX7-HR-p2#comment-354

### Steps to reproduce:

1. Install and activate GLA
2. Hover over WooCommerce Marketing Menu
3. View GLA above Coupons

### Expected behavior:

* Coupons should be at the top below Overview with marketing extensions menu its sitting below.

### Additional details:

* I expect this will likely be a change required in Core but I'm opening here to track the change in relation to GLA and for assigning to one of our team members.
* A priority ordering might need to be set up in core.

**Comment by eason9487** [comment]
This issue is more complex than it seems, and there might be some historical factors involved, so simply adding `position` to Coupons to adjust the priority will still not solve the issue completely. Fixing it from the WC core would require changing a much larger range of code and possibly even bringing breaking changes. Therefore, I tried to make some adjustments from GLA first to achieve the goal. More details were recorded at:

https://github.com/woocommerce/google-listings-and-ads/blob/67dbbcd7ff3bf6402e3c58935ffb0cf8b7c7a78b/src/Menu/MenuFixesTrait.php#L17-L84
