### ISSUE TITLE
PHP 8.1 deprecated codes

### ISSUE THREAD

**Issue by betayazilim** [woocommerce/google-listings-and-ads#1745]
Hi there,

I use PHP 8.1 and latest versions of WP and WC.
Here is the error I got with Qery monitor plugin.

Deprecated	Return type of Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\ISO3166\ISO3166::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	1	
wp-content/plugins/google-listings-and-ads/vendor/league/iso3166/src/ISO3166.php:111
Plugin: google-listings-and-ads
Deprecated	Return type of Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\ISO3166\ISO3166::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice	1	
wp-content/plugins/google-listings-and-ads/vendor/league/iso3166/src/ISO3166.php:123
Plugin: google-listings-and-ads

**Comment by mikkamp** [comment]
Thanks for the report. Since the deprecation notice is coming from one of the libraries we use, it seems we'll need to update to a newer version.

It looks like this has been addressed in version 4.0.0 of the iso3166 library: https://github.com/thephpleague/iso3166/releases
We are still on version 3.0, so we'll need to upgrade to prevent the notice.
