### ISSUE TITLE
Brand, EAN, MPN integration

### ISSUE THREAD

**Issue by betayazilim** [woocommerce/google-listings-and-ads#1746]
Hi there,

We are at year 2022 and woocommerce still doesn't support Brand, EAN, MPN.
Which are required by google, facebook or any other platform.

We use attributes for Brand, EAN, MPN.
So we want to map attiributes with this plugin.
It will be much easier to add Brand, EAN, MPN to each SKU one by one.

**Comment by mikkamp** [comment]
Thanks for the report. For enhancement / feature requests it's best to add them here: https://woocommerce.com/feature-requests/google-listings-and-ads/
Which gives us the option to track votes. Attribute Mapping happens to be the most popular requested feature so we've been working on it's implementation for a while already (coming soon).

Since we are already tracking it in GitHub I'm going to close this issue in favour of #1648
