### ISSUE TITLE
Update label when there is no data in Attribute Mapping Table

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1830]
This is a follow up for https://github.com/woocommerce/google-listings-and-ads/pull/1821 

Related to https://github.com/woocommerce/google-listings-and-ads/issues/1813

In concrete. The first point in which is required to change the label when the Attribute Mapping table has no rules. This request required a change in WooCommerce components.The change was already approved and merged https://github.com/woocommerce/woocommerce/pull/36124

However, it requires tu bump woocomemrce/components to the new released version. After updating WooCommerce COmponents we can perform this task.

### Expected behavior:

When there is no data in attribute mapping table it shows

"You have no attribute rules"

### Actual behavior:

When there is no data in attribute mapping table it shows

"No data to display" 

## Additional details

After woocommerce/components gets released and updated here we can just update the prop `emptyMessage` in the table component to perform this task.

**Comment by mikkamp** [comment]
I don't think this issue needs to be on-hold any longer. Although @puntope can you confirm whether `woocommerce/components` needs to be bumped?
Last time it was specifically bumped was a while ago: https://github.com/woocommerce/google-listings-and-ads/blame/develop/package.json#L21

From my understanding the components will load from the currently installed WooCommerce version which should have already included this change beyond L-2.

When I add the following to `js/src/attribute-mapping/attribute-mapping-table.js`
```js
							emptyMessage={ __(
								'You have no attribute rules',
								'google-listings-and-ads'
							) }

```

I see it showing up in the UI:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/53db5e24-9354-46d2-a08e-f387504bd1f6)

Can we double check if the component bumping is needed otherwise it sounds like we can just roll out a quick fix for this.

**Comment by puntope** [comment]
I will work on this today @mikkamp
