### ISSUE TITLE
Customer effort score prompt is showing undefined

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1836]
### Describe the bug:

After completing setup onboarding and we get redirected to product feed page, the customer effort score prompt shows "undefined". When we click on the "Give feedback" button, the modal shows up with two rows of feedback response.

📹 Demo video of the issue:

https://user-images.githubusercontent.com/417342/210250194-10b227e8-f763-409f-8dd1-35a2e1d5eb39.mp4

I believe this issue is related to issue https://github.com/woocommerce/woocommerce/issues/35124 and PR https://github.com/woocommerce/woocommerce/pull/35680 where the CustomerEffortScore component has been changed. The PR is included in https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.1.

I can reproduce this issue using WooCommerce trunk branch (I tested with commit d4ce6faf1eaf40d45d339498cdb9c6badb5d28f2). I tried to test it with https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.2 and https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.1 but there are TypeScript build errors (see woo-monorepo slack message p1672670905755799-slack-C03CPM3UXDJ).

This issue does not happen with WC https://github.com/woocommerce/woocommerce/releases/tag/7.2.2. The following is a demo video using WC 7.2.2 and it shows CES working as expected, with label in the prompt, and title and question in the modal:

https://user-images.githubusercontent.com/417342/210254098-ed625087-9ffb-445a-b34a-1b7711c4f757.mp4

### Steps to reproduce:

Pre-condition: Use the abovementioned WooCommerce version.

To test this issue easily, you can modify the following line:

https://github.com/woocommerce/google-listings-and-ads/blob/161f254dc243b6967fbbe78be030d9ba500947a7/js/src/product-feed/index.js#L54

with:

```js
			{ ( true || canCESPromptOpen ) && (
```

to force the Customer Effort Score prompt to show up when you navigate to the Product Feed tab.

1. Navigate to Product Feed page: `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fproduct-feed`
2. You should see the issue as shown in the demo video.

### Expected behavior:

There should be a clear CES question in the prompt.

### Actual behavior:

The CES prompt says "undefined".

**Comment by puntope** [comment]
Thanks for opening this issue @ecgan 

I commented in the mentioned PR some extra thoughts https://github.com/woocommerce/woocommerce/pull/35680#issuecomment-1369403269

For the next points of failure in the new component:

- Undefined title and invisible title inside modal could be solved by adding 

`title={ __( 'Please share your feedback', 'google-listings-and-ads' ) }`

- First question label could be fixed by adding 

`firstQuestion={ label }`

- The only one which is problematic is that `secondQuestion` is now mandatory. I tried to hide it with CSS but when I share the feedback I'm not able to send it since there is a check in the component internals. 

Option A - I would suggest to add a generic second question, maybe "How is you experience with the plugin overall?"

Option B - relies on waiting for team Mothra to fix the component.
