### ISSUE TITLE
aggiornamento alla versione 2.3.10, ho il tema woosmart, ho fatto l'aggiornamento e mi ha creato un errore critico, perchè?

### ISSUE THREAD

**Issue by marinellalibbra** [woocommerce/google-listings-and-ads#1898]
ho il tema woodMart, ho fatto l'aggiornamento del plugin alla versione 2.3.10 e mi ha creato un errore critico, perchè?
### Steps to reproduce:

1. 
2. 
3.

**Comment by puntope** [comment]
Hello @marinellalibbra 

Thanks for contacting us. I'd suggest to [create a ticket with WooCommerce support team](https://woocommerce.com/my-account/create-a-ticket/) in order to provide you further assistance and guidance with your particular problem. If there is a bug in the plugin and not an issue with your theme we will follow up from there. 

You can also provide us the critical error but probably better to reach support.
