### ISSUE TITLE
Custom prefix to $title

### ISSUE THREAD

**Issue by art-n** [woocommerce/google-listings-and-ads#1951]
Hi there,

I'd like to add statics prefix and suffix to product title.

I've tried with this snippet :
```
function gla_custom_product_title( $item_data, $product ) {
    if ( isset( $item_data['title'] ) ) {
        $custom_title = 'Static1' . $item_data['title'] . ' Static2';
        $item_data['title'] = $custom_title;
    }
    return $item_data;
}
add_filter( 'woocommerce_gla_feed_item_data', 'gla_custom_product_title', 10, 2 );
```

Doesn't work.

Any idea ?

Thank you !

**Comment by mikkamp** [comment]
Hi @art-n 

I imagine you are looking for the hook `woocommerce_gla_product_attribute_values` instead of `woocommerce_gla_feed_item_data`, see here: https://github.com/woocommerce/google-listings-and-ads/blob/2.4.2/src/Product/WCProductAdapter.php#L144-L167

Also for overriding the attribute you'll need to get the original title from the product, and it won't be set in the array so you'll need to change the conditional logic.

Having said that, this repository is not intended for support requests. You could try posting a support request in the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/). Although generally we can't provide support on custom code snippets.

So I'll go ahead and close this issue for now.
