### ISSUE TITLE
Deletes and overwrites shipping info in google merchant center?

### ISSUE THREAD

**Issue by webwit** [woocommerce/google-listings-and-ads#2053]
### Describe the bug:
Deletes and overwrites shipping info in google merchant center? Not sure if this plugin does that or something else.

### Steps to reproduce:
I run the latest Wordpress + Woocommerce + plugin versions. I also have the Flexible Shipping plugin to handle some special cases. In Google Merchant center I mirrored those cases to set up correct shipping info and rates, by adding new shipping services. I also edit some existing ones added by Google Listings and Ads, for example because it has stuff wrong like order cutoff time, order handling time, and adds prices without VAT while it should be with VAT.

Then some days later all my shipping methods are reset and custom ones deleted. I only see entries created by Google Listings and Ads without my fixes for VAT.

### Expected behavior:
I don't want GLA to touch my custom settings or any of these settings at all.

### Actual behavior:
It touched my custom settings and deleted shipping services, causing my ads not to display or to display wrong shipping info.

**Comment by mikkamp** [comment]
Hi @webwit 

Shipping Settings syncing is done during onboarding but also if any shipping setting is updated / added in WooCommerce.

From what I understand you originally synced shipping settings and then edited them in Google as there were several ones that were incorrect. Because shipping syncing is enabled those would eventually get overwritten when a new sync is triggered.

If you've added custom shipping services in the Merchant Center then they shouldn't be deleted (as far as I'm seeing from the sync code). Could you provide some more information / screenshots of which shipping services you have setup in WooCommerce and how they end up in your Merchant Center account.

If you do want to tweak shipping settings in your Merchant Center, I'd suggest to disable syncing of shipping settings afterwards. You can do so by going to Marketing > Google Listings & Ads. On the Dashboard page with the list of Programs you should see a Free Listings entry. If you click on the edit button there then you can adjust the shipping settings.

![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/b1024b21-f77e-44af-9b71-efcfbb7a24e8)

You'd want to select the last option.

![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/0182b104-73a1-4814-8d9c-98d7aa891f35)

Can you confirm if that prevents any new changes from being overwritten?

**Comment by webwit** [comment]
Thanks Mikkamp, that setting is exactly what I needed, so sorry for not finding it myself. I think this can be closed, unless you want to put it on a todo list to make it easier to discover.

We edited the shipping methods in the Google Merchant Center since those entries were deleted, I think by adding new ones manually and tweaking existing ones added by Google Listings & Ads, and then didn't touch anything. So far so good.

P.S. GL&A probably still gets the tax wrong for my country (NL). If the plugin adds that info, the shipping costs show in Google Ads without tax while my shop for consumers should list it with tax like ads from competitors. I had to fix that manually in the merchant center before.

**Comment by mikkamp** [comment]
Thanks for the reply. Glad to hear that's working for you, so I'll go ahead and close this issue then.

I've noted your mention on taxes. Currently the plugin is only setup to handle taxes for the US.
So unfortunately taxes for any other countries (unless prices are defined including taxes) will need to be amended manually.
