### ISSUE TITLE
No option to reconnect to WordPress.com after Jetpack disconnection

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#2284]
### Describe the bug:

We rely on the Jetpack connection package to establish a connection between Google Listings & Ads and WordPress.com. While we do not offer an option to disconnect Jetpack, Jetpack can get disconnected in the following ways:

* Connection issue - something hindering/breaking the Jetpack connection
* Jetpack can be disconnected using the Jetpack debugger (Internal tool: Happiness uses this tool if a customer wants to change the connected JP account)
* Jetpack can be disconnected by the user from WordPress.com

When Jetpack gets disconnected in any of the above ways, we do not offer the option to reconnect Jetpack. Instead, users are presented with a blank screen and the error `There was an error loading Google account info. Please reconnect Jetpack`

![qkOlhf.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/f78836fe-b8d8-4905-8577-ac79af1936c9)

### Steps to reproduce - approach 1:

1. Setup Google Listings & Ads and all required connections without Jetpack plugin
2. Go to the JP debugger Pc9OEs-v-p2 and disconnect the Jetpack connection with the tool or disconnect the Jetpack connection from WordPress.com
3. Go to Marketing > Google Listings & Ads. Notice the error "Please add your phone number" and "Please add your store address" is returned in the contact information section. (I notice this error is removed after a while and a blank screen is shown as in "approach 2" below)
4. Notice no option to reconnect Jetpack is shown
5. Go to the test connection page and disconnect MC by clicking "MC Disconnect". 
6. Return to Marketing > Google Listings & Ads notice the following error is returned:

![z3KApH.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/e119bdf6-db26-4017-a0a0-d580ad1f0300)

7. Return to the test connection page and attempt to `disconnect Google account` and notice the response "Please reconnect your Jetpack account." is returned. (If this disconnection is possible, it would show the first step of the setup screen but still won't show the option to reconnect to WordPress.com. See approach 2 below)

### Steps to reproduce - approach 2:

1. Setup Google Listings & Ads and all required connections without Jetpack plugin
2. Go to Marketing > Google Listings & Ad > Settings and click Disconnect from all accounts (This removes GMC and MC connection as expected)
3. Go to the Jetpack debugger and disconnect the Jetpack connection with the tool or disconnect the Jetpack connection from WordPress.com
4. Go to Marketing > Google Listings & Ads. Notice the blank screen with a "spinning circle" and the error `There was an error loading Google account info. Please reconnect Jetpack`:

![2Ur8Hg.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/58251249-dbca-4537-b5e5-06ac7fd34bb1)
7. Notice there's no way to reconnect to WordPress.com

### Expected behavior:

The option to reconnect to WordPress.com should be shown when the Jetpack connection is disconnected or broken. 

### Actual behavior:

The option to reconnect to WordPress.com isn't shown. 

### Additional info

Based on my test, the only way to reconnect Jetpack is to install the Jetpack plugin:
- On activation, it shows a prompt to fix the broken Jetpack connection. After fixing it, you can reconnect to WordPress.com via GL&A.
- Even if the above prompt isn't shown - initiating a JP connection through the Jetpack plugin would offer the option to reconnect to WordPress.con in GL&A

**Comment by mikkamp** [comment]
### Steps to reproduce - approach 2
Thanks for the report. I'm able to reproduce the scenario in your second step. Some more details about what's happening:

On the onboarding page step 1, it does several request in order to check which accounts are connected:

1. `/wp-json/wc/gla/jetpack/connected`
This request only looks for a local Jetpack token which is fetched from the database. Since we previously did have a valid Jetpack token, but we broke the connection externally (using the Jetpack debug tool), the Jetpack token isn't cleared up in the local database. So this request still has what it assumes is a valid token and returns a "connected" response

2. `/wp-json/wc/gla/google/connected`
This request needs to get some data from the WCS so it will send an external request using the Jetpack token to authenticate. Note, at this point this Jetpack token is still available in the local DB but it's invalid when checked externally. So we get a permission denied error, which our 401 handler picks up and returns an `AccountReconnect::jetpack_disconnected` response:
```json
{
    "message": "Please reconnect your Jetpack account.",
    "status": 401,
    "code": "JETPACK_DISCONNECTED"
}
```
The UI doesn't handle this specific scenario because it assumed the Jetpack connection was valid from the response returned in step 1. Nor does it clean up the token from Jetpack, which remains intact in the DB for the next request.

#### Actions to consider taking:
- Should we clean up a Jetpack token from the database / attempt a soft disconnect, if we got an external response that the token wasn't valid?
- Can we handle all requests during the onboarding and redirect them to step 1 to reconnect the Jetpack / Google account depending on the type of 401 response? Seems like [we already have this handler](https://github.com/woocommerce/google-listings-and-ads/blob/2.6.0/js/src/data/index.js#L32-L62) but it requires `glaData.mcSetupComplete` to be true otherwise it doesn't handle the redirect.

#### Workaround to resolve this scenario
- Temporarily install and activate Jetpack
- Go to Jetpack > My Jetpack
- Scroll down to Connection section and disconnect
- Restart the GLA onboarding to once again reconnect the WordPress.com account

Can also be restored by clearing up the Jetpack token in the DB but we don't have an easy tool for that.

### Steps to reproduce - approach 1
I'm not able to reproduce these steps. As when I disconnect the Jetpack connection externally I get the same [handler](https://github.com/woocommerce/google-listings-and-ads/blob/2.6.0/js/src/data/index.js#L32-L62) to redirect me to reconnect my WordPress.com account:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/7911b7c0-31a2-437e-8d2e-e77b0c745de3)

Based on the handler it should catch any 401 response and then check if it should redirect. Can you open confirm what the network requests are when you check in the developer console.

From your screenshot it looks like you should be seeing a request to:
`/wp-json/wc/gla/mc/contact-information` that should return a 401 response with the following content:
```json
{
    "message": "Please reconnect your Jetpack account.",
    "status": 401,
    "code": "JETPACK_DISCONNECTED"
}
```

Can you confirm you are seeing that being returned?

@eason9487 It seems we are using a [Middleware for apiFetch](https://github.com/woocommerce/google-listings-and-ads/blob/2.6.0/js/src/data/index.js#L32-L62) to handle the 401 status and then redirect them. Is there any circumstances where Middlewares can conflict or be overwritten by another plugin? Based on this screenshot it looks like there are multiple 401 errors being returned but neither of them is activating a redirect:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/408ef3ed-64f9-4ce6-abd6-56275e9d6b74)
In my site it redirects right after receiving the first 401.

**Comment by eason9487** [comment]
Hi @mikkamp

> It seems we are using a [Middleware for apiFetch](https://github.com/woocommerce/google-listings-and-ads/blob/2.6.0/js/src/data/index.js#L32-L62) to handle the 401 status and then redirect them. Is there any circumstances where Middlewares can conflict or be overwritten by another plugin?

Technically it could, but I think it doesn't usually happen as it should be an anti-pattern. On the other hand, if it does, it should be possible to identify it through a conflict test.

> Based on this screenshot it looks like there are multiple 401 errors being returned but neither of them is activating a redirect

The approach 1 seems to be issue #1972. The middleware for `apiFetch` did handle the 401 status and redirect to the reconnection flow. However, the reconnection flow redirects back to Setting page due to the inconsistent Jetpack connection status. These redirections could happen in a flash, so it ends up looking like it's stuck on the Setting page with forever loading. The additional details section in #1972 has a rough code trackback.

**Comment by mikkamp** [comment]
> The approach 1 seems to be issue https://github.com/woocommerce/google-listings-and-ads/issues/1972. The middleware for apiFetch did handle the 401 status and redirect to the reconnection flow. However, the reconnection flow redirects back to Setting page due to the inconsistent Jetpack connection status. These redirections could happen in a flash, so it ends up looking like it's stuck on the Setting page with forever loading.

Thanks for clarifying, I'm able to reproduce it now with the steps in #1972
I have some changes I'm testing out which forces the function `is_jetpack_connected` to do a token validation through an external request (Jetpack token validation), so it can return the `disconnected` status in those cases. This should make it easier for the UI to handle those scenarios correctly.
