### ISSUE TITLE
Defining delete plugin data constant triggers a fatal error

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#2285]
### Describe the bug:

When the Jetpack connection is broken or disconnected, defining a constant to delete the plugin's data triggers a fatal error.

### Steps to reproduce:

1. Disconnect Jetpack through any of the approaches in this issue: https://github.com/woocommerce/google-listings-and-ads/issues/2284
2. Define a constant to delete the plugin's data by adding the following code snippet to wp-config.php: 
`define( 'WC_GLA_REMOVE_ALL_DATA', true );`
3. Go to Marketing > Google Listings & Ads and notice the following error:

![x4gtJW.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/f1198032-6f0a-4b07-8f69-dc240f3f8616)

4. Check the site's recent fatal error log in WooCommerce > Status > Logs and notice the following error:

`2024-02-28T14:21:21+00:00 Critical Uncaught Automattic\WooCommerce\GoogleListingsAndAds\Exception\AccountReconnect: Please reconnect your Jetpack account. in /home/sundayistesting/public_html/wp-content/plugins/google-listings-and-ads/src/Exception/AccountReconnect.php:26 CONTEXT: {"error":{"type":1,"file":"\/home\/sundayistesting\/public_html\/wp-content\/plugins\/google-listings-and-ads\/src\/Exception\/AccountReconnect.php","line":26},"backtrace":["","#0 \/home\/sundayistesting\/public_html\/wp-content\/plugins\/google-listings-and-ads\/src\/Internal\/DependencyManagement\/GoogleServiceProvider.php(237): Automattic\\WooCommerce\\GoogleListingsAndAds\\Exception\\AccountReconnect::jetpack_disconnected()","#1 \/home\/sundayistesting\/public_html\/wp-content\/plugins\/google-listings-and-ads\/src\/Internal\/DependencyManagement\/GoogleServiceProvider.php(209): Automattic\\WooCommerce\\GoogleListingsAndAds\\Internal\\DependencyManagement\\GoogleServiceProvider->handle_unauthorized_error(Object(Automattic\\WooCommerce\\GoogleListingsAndAds\\Vendor\\GuzzleHttp\\Psr7\\Request), Object(Automattic\\WooCommerce\\GoogleListingsAndAds\\Vendor\\GuzzleHttp\\Psr7\\Response))","#2 \/home\/sundayistesting\/public_html\/wp-content\/plugins\/google-listings-and-ads\/vendor\/guzzlehttp\/promises\/src"]}`

### Expected behavior:

Adding a constant to completely delete the plugin's data shouldn't trigger any fatal error.

### Actual behavior:

It's triggering a fatal error.

### Support interactions

* https://wordpress.org/support/topic/unlink-wordpress-account/#post-17207809
* 7750761-zd-a8c

### Additional information

It's possible there are other ways to trigger the fatal error. However, this is the method I discovered to trigger it.

**Comment by mikkamp** [comment]
Thanks for recording the details, I'm able to reproduce this fatal error.

On the onboarding page step 1, it does a request to confirm if the WordPress.com account is connected:

`/wp-json/wc/gla/jetpack/connected`
This request only looks for a local Jetpack token which is fetched from the database. Since we previously did have a valid Jetpack token, but we broke the connection externally (using the Jetpack debug tool), the Jetpack token isn't cleared up in the local database. We used the constant `WC_GLA_REMOVE_ALL_DATA` which removed all GLA data but the token is owned by Jetpack connect, so we don't clear this up.

Since we did clear up the option `WP_TOS_ACCEPTED` we trigger the following code to log a new TOS accepted for WP: https://github.com/woocommerce/google-listings-and-ads/blob/2.6.0/src/API/Site/Controllers/Jetpack/AccountController.php#L172-L174
Locally we assume Jetpack is connected but since the token is no longer valid (disconnected externally) it throws an exception which we don't catch.

#### Suggested steps to resolve:
- Catch the error and return a status "disconnected". Allowing the UI to reconnect.
- Make this connected handler more robust by actually sending an external request to the WCS (which will validate the status of the local token). Sending a request to fetch the date of the last time WP TOS was accepted would be a simple test.
