### ISSUE TITLE
Update Jest tests for Set up paid ads flow

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2579]
>[!CAUTION]
> This is blocked by #2534, #2535, and #2536.

As a follow-up to the changes to streamline the paid ads flow defined in #2460, The related Jest tests will need to be updated once changes from the following issues are completed:

- https://github.com/woocommerce/google-listings-and-ads/issues/2534
- https://github.com/woocommerce/google-listings-and-ads/issues/2535
- https://github.com/woocommerce/google-listings-and-ads/issues/2536

## Acceptance criteria

- JS Unit tests related to the updated Ads Setup flow are passing (ex: https://github.com/woocommerce/google-listings-and-ads/actions/runs/10706073441)

## Implementation details
This work should branch from the [feature/2460-simplify-paid-ads-setup](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2460-simplify-paid-ads-setup) branch once each of the related issues listed in the overview of this ticket have been merged.

There is an AdsStepper test at `js/src/setup-ads/ads-stepper/index.test.js` that is currently failing.

**Comment by asvinb** [comment]
@joemcgill @kt-12 The failing test was fixed in the following PR:
https://github.com/woocommerce/google-listings-and-ads/pull/2623/files#diff-c10ae52d5079fec4d79e7e3a503fd239e7c34f2f23567d3ed563dc818cf6cee0R42

I don't think there is anything else to do here. Furthermore, all tests pass on the [feature/2459-campaign-creation-flow](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2459-campaign-creation-flow) branch.

**Comment by joemcgill** [comment]
Closing this as redundant now that this has been addressed in #2595 and #2632.
