### ISSUE TITLE
Speak the same currency

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#363]
## User story
All parts of the code should speak the same currency (as we don't want to do any conversions).

When we create an ads account through the API we pass along the [WC store currency](https://github.com/woocommerce/google-listings-and-ads/blob/0.3.0/src/API/Google/Proxy.php#L306). However when we link an ads account we do not check the account currency. As part of the linking we should check/warn the user about mismatching currencies.

If we are going to allow the ads account to be in a different currency then we need to make sure we display all prices (reports, budget estimation, campaigns) using the ads account currency, instead of the WC store currency.

In the WC Admin reports, amounts are sent through as a decimal number without formatting. It then uses some values stored in the page `var wcSettings` and some helper functions to convert the amount to a formatted price string. Can we reuse these same functions? In the mocked reports it's currently expecting a formatted price string, however in the [reports PR](https://github.com/woocommerce/google-listings-and-ads/pull/251) we are returning them as decimal numbers.

**Comment by mikkamp** [comment]
Update:
#795 adds the Ad Account currency to the `/wc/gla/ads/connection` endpoint.
```
{
    "id": 6111390429,
    "currency": "EUR",
    "status": "connected"
}
```

The store currency is already available in the UI. So what's missing now is a warning / notification to the user when those two currencies don't match.

**Comment by eason9487** [comment]
> Update: We already resolved the currency being used on the UI pages, it's all using the Store currency.
> 
> So the pending point would be to implement either one of these two:
> 
> 1. Check Ads account currency (display warning if it doesn't match store currency)
> 2. Support displaying currency used in Ads account (not going to support for v1)

Hey @j111q, for option 1, we probably need some visual design to add warnings to dashboard, report, and campaign creation/edit pages. Since there are many places to display prices on each page, would it be a good idea to consider displaying a warning on the top of each page?

About option 2, I was thinking it probably has to be implemented. Otherwise, only giving the warning from option 1, the price information still looks confusing.

![image](https://user-images.githubusercontent.com/17420811/124249736-bda04600-db56-11eb-8028-71ae1a5958fb.png)

An additional question is that although implementation option 2 makes the currency display correctly, some of the currency symbols are the same, so perhaps it is still necessary to display the warning whenever the ads account currency is different from the WC store currency. Or, maybe display all price strings with the currency alphabetic code instead of currency sign? Thus, we might only need to add a new FAQ to explain it without showing the warning.

**Comment by j111q** [comment]
Interesting question. 

> Check Ads account currency (display warning if it doesn't match store currency)
> Since there are many places to display prices on each page, would it be a good idea to consider displaying a warning on the top of each page?

What kind of warning would that be? 
What do we want users to do - go into the campaign to edit the currency? 
If they don't change it, what would happen? Would we pause all their campaigns until they change it? Or, for example, would it cause some kind of billing error each month? 

> Or, maybe display all price strings with the currency alphabetic code instead of currency sign?

I do think this sounds better!

**Comment by mikkamp** [comment]
The user can't really take any action, because a currency can't be set for a [CampaignBudget](https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignBudget). Changing the currency on the account is not available as mentioned [here](https://support.google.com/google-ads/answer/9841530?hl=en), so they would have to create a new ads account.

So both when creating a campaign and viewing campaign report data, the budget and costs amounts will be in the account currency, even though we display it using the store currency. We need to make this difference clear to the user, so they don't interpret the information incorrectly. Or for example setup a campaign for a 1000 JPY when their ads account is actually set to USD, that could end up more costly then they expected.

There are also cases where it's more subtle and they won't notice for example CAD and USD would both show with `$`

The create/edit campaign seems to already show a 3 letter currency code, so maybe we should just switch that to Ads account currency (same for other locations where we display the campaign budget). And then we can have a generic warning that the report currencies could be mixed on the dashboard/report pages. Mixed would mean sales are recorded in store currency and spend is recorded in Ads account currency.

**Comment by j111q** [comment]
>The create/edit campaign seems to already show a 3 letter currency code, so maybe we should just switch that to Ads account currency (same for other locations where we display the campaign budget).

Yes to this.

>And then we can have a generic warning that the report currencies could be mixed on the dashboard/report pages. Mixed would mean sales are recorded in store currency and spend is recorded in Ads account currency.

Got it, yeah let's do this. I do hope it would be quite an edge case. 

**Copy for the warning:**

`Note: The currency set in your Google Ads account is AAA, which is different from your store currency, BBB. [Read more](https://support.google.com/google-ads/answer/9841530?hl=en)`

LMK if this is ok!

**Comment by eason9487** [comment]
> Or for example setup a campaign for a 1000 JPY when their ads account is actually set to USD, that could end up more costly then they expected.

Just notice this problem is more critical than I originally thought. My ads account is set to **USD**, and my store currency is using **JPY**. In this case, a very large campaign budget setting error would occur:

1. In the campaign creation page, it shows **JPY** currency on the input field, and the recommended budget range below is shown in JPY as well. 
    ![2021-07-20 13 23 04](https://user-images.githubusercontent.com/17420811/126267059-8eb671ea-d3a2-4885-82ee-ef9c615cb9a2.png)
2. After creating the campaign with **1,000 JPY** daily budget, it shows the same 1,000 JPY on the programs table.
    ![2021-07-20 13 26 10](https://user-images.githubusercontent.com/17420811/126267324-462af94c-30cb-413d-9ef2-3d8ed096fc56.png)
3. But it actually is **1,000 USD** daily budget at Google Merchant Center. (Viewed from https://merchants.google.com/mc/campaigns?a=your_mechant_account_id)
    ![2021-07-20 13 27 06](https://user-images.githubusercontent.com/17420811/126267557-05e3b87b-d159-4cf5-9e44-b66896c1b2b5.png)

❗  That would cause more than 100 times the difference in ads campaign spend.

**Comment by eason9487** [comment]
> a currency can't be set for a [CampaignBudget](https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignBudget).

Since it cannot specify the budget currency when creating campaigns, to fix this https://github.com/woocommerce/google-listings-and-ads/issues/363#issuecomment-883081178 problem, a solution could be:
- Change the whole budget section UIs to use the ads account currency
    - "Daily average cost" input
    - "Monthly max, estimated" input
    - recommended budget range text
- Change the `ads/campaigns/budget-recommendation` API to use the ads account currency
    - https://github.com/woocommerce/google-listings-and-ads/blob/1.2.1/src/API/Site/Controllers/Ads/BudgetRecommendationController.php#L64

**Comment by tomalec** [comment]
> #795 adds the Ad Account currency to the `/wc/gla/ads/connection` endpoint.

Can we get it, and how cheap is the currency for the other endpoints? For the dashboard and report pages, we already make a number of API requests (~8), and the data coming from 5 they are not complete without currency.

So my first idea is to add 9th request to `/wc/gla/ads/connection` and block the rendering summary, reports, programs list before we get this response as well.

But I wonder, maybe report API exposes currency as well, so it could be forwarded without a need to make additional calls?
