### ISSUE TITLE
WordPress.com linked account shows as blank when viewing settings as a non jetpack owner admin user

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#624]
### Describe the bug:

On the settings page,  WordPress.com linked account shows a blank email when logged in NOT as the main JP connected site user.

<img width="1434" alt="Screen Shot 2021-05-18 at 3 57 00 pm" src="https://user-images.githubusercontent.com/355014/118602726-2ffcd700-b7f2-11eb-84b7-8e8f912c9170.png">

Notes
* We only rely on the "site connection" so this doesn't impact the use of the extension - but we may want to put some placeholder text in place here or something to indicate contacting jetpack owner
* Non jetpack owner admins can still disconnect jetpack - so I think we are ok to still show the disconnect/settings page

---

The jetpack dashboard shows the following

<img width="1100" alt="Screen Shot 2021-05-18 at 4 12 28 pm" src="https://user-images.githubusercontent.com/355014/118604180-02b12880-b7f4-11eb-86a3-05b2bd2f4b26.png">

<img width="1115" alt="Screen Shot 2021-05-18 at 4 11 15 pm" src="https://user-images.githubusercontent.com/355014/118604239-15c3f880-b7f4-11eb-9dbe-30572aa23f34.png">

### Expected behavior:

Thoughts on what to display here @j111q ?

### Steps to reproduce:

1. Connect a site up to the JP, Google, etc.
2. Create a new admin user and log in as that user
3. Go to the  Google Listings and Ads > Settings

**Comment by mikkamp** [comment]
This is also evident in the onboarding steps. A valid token is available so they can proceed with connecting the Google and MC accounts. But we don't show any information about the connected WordPress.com account.

![image](https://user-images.githubusercontent.com/11388669/123083887-73adb680-d418-11eb-8c5b-da8c5efc9937.png)

Originally reported in: https://wordpress.org/support/topic/missing-connect-button-for-woocommerce-com-account/

**Comment by dphyled** [comment]
Just adding that [the user confirmed installing/connecting Jetpack fixed the issue](https://wordpress.org/support/topic/missing-connect-button-for-woocommerce-com-account/#post-14594102) with the missing WordPress.com connection info/button in the settings! Thank you for closing out the forum thread, Jason! 😄🙇

**Comment by mikkamp** [comment]
The API endpoint already takes this into consideration using the `owner` parameter. Here is the response from
`GET /wc/gla/jetpack/connected`

```json
{
	"active": "yes",
	"owner": "no",
	"displayName": "",
	"email": ""
}
```

When we are the owner the response would look like:
```json
{
	"active": "yes",
	"owner": "yes",
	"displayName": "John Doe",
	"email": "john@doe.email"
}
```

So we'll just need some adjustments in the UI to show some alternative text if active is `yes` and owner is `no`. It would need to be changed [here](https://github.com/woocommerce/google-listings-and-ads/blob/1.1.0/js/src/setup-mc/setup-stepper/setup-accounts/wordpressdotcom-account/card-content.js#L33) and [here](https://github.com/woocommerce/google-listings-and-ads/blob/1.1.0/js/src/settings/disconnect-accounts/index.js#L94)

My suggestion would be just to show some simple text like "connected" instead of the email. @j111q Is there some better text to show in those two places?

**Comment by j111q** [comment]
Apologies for the late reply on this and thanks @eason9487 for chatting it through with me 🙏 

Let's use `Successfully connected through Jetpack` for the text. 
So that IF they really need to disconnect for whatever reason, they know they can go to their Jetpack connection to do so. But hopefully that would be a very uncommon scenario.
