### ISSUE TITLE
Handle Jetpack/WPCOM account disconnect and prompt user to reconnect

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#775]
### Describe the bug:

If a merchant has GLA setup (and Jetpack Installed) and then they remove Jetpack (and disconnect the connection) the GLA UI will stop working (and I assume some of the underlying functionality - without diving in very deep) - failed requests to WCS.

We need a way to catch the disconnect and prompt a user to reconnect - especially when viewing the UI.

Related to https://github.com/woocommerce/google-listings-and-ads/issues/486

I think one of the ideas was to have a global/central way to handle account connectivity and prompt users to reconnect any accounts that become disconnected.

**Comment by tomalec** [comment]
Here is an example of a merchant experiencing such a problem 4203273-zd-woothemes

It seems there is no error message displayed in the UI even suggesting the Jetpack is an issue but,
- Dashboard and Reports pages throw errors
- Paid Performance Card is forever loading
	
	![image](https://user-images.githubusercontent.com/17435/128548552-9ee3f253-5f28-4dac-8ef1-bec664defdb0.png)

- Settings are forever loading
	
	![image](https://user-images.githubusercontent.com/17435/128548412-e0518811-6574-4d2f-b455-6f5fb660a872.png)

- Product Feed redirect to an empty `/wp-admin/admin.php?page=wc-admin&subpath=%2Freconnect-accounts&path=%2Fgoogle%2Fsettings`
	
	![image](https://user-images.githubusercontent.com/17435/128548466-0c4c3e00-1580-4c02-92dd-6192f9bae06f.png)

**Comment by mikkamp** [comment]
We have the design specs ready how this should be handled in the UI: pcTzPl-mN-p2

However before that's implemented the initial stage would be to detect we've been disconnected in the backend, so we can flag to the UI that a reconnect is needed.

We have a similar "global" connection status for the Google account. In the backend we keep track of this using the GOOGLE_CONNECTED option, whenever we receive a 401 error from a WCS request (proxied or direct), we [mark the option as false](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Internal/DependencyManagement/GoogleServiceProvider.php#L196-L198).

In the UI this handled with the following logic:
> If any API endpoint starts with '/wc/gla' and it responds with HTTP status code 401, the frontend side will forcibly redirect the webpage to the Google accounts reconnection page.

The easier path to take would be to duplicate the code we have now, but use a [407 error](https://httpstatuses.com/407) when the Jetpack / authentication token is not valid. See additional discussion here: p1646222044607379-slack-CK365S85V

Ideally we would return an error response along the lines of:
```js
{
    status: 401,
    code: "JETPACK_DISCONNECTED"
}
```
Based on the way the code is written now, we could potentially have to handle that in each controller, so we might need to do some refactoring if that's the route we want to take.

For the backend we need to catch all the following scenarios:
1. Error when [generating an auth token](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Internal/DependencyManagement/GoogleServiceProvider.php#L216-L217) during the creation of a request
2. When any request is sent to the WCS we have several cases where a 401 unauthorized response is returned, see [here](https://github.com/Automattic/woocommerce-connect-server/blob/woogle/lib/jp-authentication/index.js). Since that's a 401 that will currently trigger to reconnect their Google account, but in those cases we need to prompt them to reconnect their WordPress account
