### ISSUE TITLE
Shortcodes appear in product descriptions

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#784]
### Describe the bug:
If a product's description uses any shortcodes, we do not remove them before syncing the product to Google Merchant Center. We do remove the HTML tags from the description.

### Expected behavior:
The product description must be submitted as plain text without any shortcode tags

### Actual behavior:
The product description contains shortcode tags

### Steps to reproduce:

1. Use shortcodes in a product's description
2. Sync the product
3. Shortcodes are still present in the product description when viewing it on Google Merchant Center

### Additional details:
Reported by a user in https://wordpress.org/support/topic/overall-plugin-%d1%81ritique/

**Comment by findingsimple** [comment]
Reopening, seems like some customers are still seeing shortcodes (or similar) https://wordpress.org/support/topic/critical-error-206/#post-14590596

**Comment by mikkamp** [comment]
Probably need to take a closer look at the Divi theme and it's shortcodes. But I assume this is happening because we use `strip_shortcodes` which only removes shortcodes which are added at the time. We sync products in the background, so the theme probably doesn't add it's shortcodes when this is done. Maybe we need to switch to a regex call, can be copied from the one within `strip_shortcodes`.
That will mean we will match any text within square brackets, but maybe that's a less common occurrence anyways.

**Comment by nima-karimi** [comment]
Hmm. I think if we remove everything within a bracket then we would have support requests complaining why random words are removed from the description. Probably best to just leave this as is and work on implementing https://github.com/woocommerce/google-listings-and-ads/issues/782 to allow users to choose the short description for their products on Google.

**Comment by findingsimple** [comment]
> allow users to choose the short description for their products on Google.

Yeah that was my first thought

**Comment by findingsimple** [comment]
Moved to a later release.
