### ISSUE TITLE
Add two CES prompts to get more product feedback 

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#882]
## What is a CES prompt?
It's a little toast that appears on the bottom left of the user's screen, asking the user for feedback on a task they've just completed. [Link to CES GitHub issue](https://github.com/woocommerce/woocommerce-admin/issues/5259)

## Prompt 1
Prompt 1 should appear immediately after User successfully completes initial setup flow.

![Setup1](https://user-images.githubusercontent.com/65582817/125259488-efbd5f00-e331-11eb-9db4-d56b2d2ebf34.png)

## Prompt 2
Prompt 2 should appear immediately after User successfully completes Ads creation flow and clicks "Got it" in the success modal.

![image](https://user-images.githubusercontent.com/65582817/125585386-2f3042c6-0cb2-44b8-a541-030cc9a17c0a.png)

## Figma link
[URL](https://mc.a8c.com/pb/29be3/)

**Comment by eason9487** [comment]
Hey @j111q, I have two questions:

1. For **prompt 1**, after completing the setup, it will show [the success modal](https://github.com/woocommerce/google-listings-and-ads/pull/632) first. And user might 1) dismiss/close the modal, 2) open the product feed page in a new tab, 3) browse to the ads setup page. If a user goes the 3) path, then they would run into **prompt 2** after finishing the ads setup continuously without going through the product feed page. So, the question is about the display timing of toast, which one is expected for **prompt 1**?
    - Show toast when the first time user entering the product page regardless of the paths they were going through
    - Show toast after the user 1) dismissing/closing the modal or 2) opening a new tab, but it would be bypassed if they 3) proceed to set up ads
    - Show toast with the modal at the same time
    - Others?
2. The survey data of CES implementation in WC-admin was recorded via event tracking. Are we going to record in the same way? If yes, should the two prompts show up only when the event tracking option is checked off?

**Comment by eason9487** [comment]
Dev note

- Library: https://github.com/woocommerce/woocommerce-admin/tree/main/packages/customer-effort-score
- Usage in WC-admin: https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/client/customer-effort-score-tracks/customer-effort-score-tracks.js#L107-L135

**Comment by j111q** [comment]
> Show toast when the first time user entering the product page regardless of the paths they were going through

This is the one we should go with, thank you for checking!! 🙏 

> The survey data of CES implementation in WC-admin was recorded via event tracking. Are we going to record in the same way? If yes, should the two prompts show up only when the event tracking option is checked off?

Yes, follow the existing implementation of CES in wc-admin. No, the prompts shouldn't show if event tracking is turned off.

**Comment by ianlin** [comment]
Hey @j111q, I've got a question when developing this feature, here's an video:

https://user-images.githubusercontent.com/914406/145521153-cf63d01d-c4e4-4c83-8fd3-942f7507f03c.mov

From the video you an see that, since the success modal has higher z-index than the CES prompt, i.e. success modal is on top of the CES prompt. We cannot click the CES prompt unless the success modal is closed. Here are different options that we can choose:

1. The above said behaviour is ok.
2. Make the CES prompt on top of the success modal so we can click it before closing the success modal. But if we click the CES prompt, the success modal will be closed.
  a. Because the current logic is: the success modal will be closed when clicking on anywhere outside of the success modal
3. Like point 2, but remove the logic of clicking anywhere outside to close the success modal. So in order to close the success modal we must click the `X` button or `Maybe later`, or pressing the `esc` key.
4. Any other ideas?

**Comment by j111q** [comment]
Thank you @ianlin for the detailed notes and video! 🤩 I think I remember discussing this with @ecgan at some point a while ago actually, haha. 

I think (1) the above behaviour is okay (although not ideal). For (2), I don't want the user to accidentally close the success modal because that should be the most important thing for them to look at in this moment of the flow, and for (3), I would rather not change the behaviour of how modals are closed for consistent behaviour across all modals. 

The "true" ideal would be for us to trigger the CES prompt at another point, like after the success modal is dismissed/closed and the user is looking at the product feed for the first time after setting up. But if I'm recalling correctly from our previous discussions, that wasn't possible. So this behaviour is okay I guess 😅 LMK if you have other ideas though!!

**Comment by ecgan** [comment]
@j111q , 

> I think I remember discussing this with @ecgan at some point a while ago actually, haha.

Do you mean the discussion comments we had in this internal P2 pbIy4N-1Jn-p2? 😄 

---

@j111q @ianlin ,

> The "true" ideal would be for us to trigger the CES prompt at another point, like _after the success modal is dismissed/closed_ and the user is looking at the product feed for the first time after setting up. But if I'm recalling correctly from our previous discussions, that wasn't possible.

Yeah I'm also thinking it would be better to trigger the CES prompt after the success modal is closed.

If we were to show the CES prompt under the modal (as shown in @ianlin's video), I think that CES prompt is quite distracting, and it might make users want to go click on the CES prompt and accidentally dismiss the modal, which we do not want to happen - we want users to go through the steps and read the things presented in the modal. 

I haven't looked at any related code yet, I think/hope that is possible. 😄 

> Any other ideas?

Based on @ianlin's video, I think the focus movement - from the success modal in the center of the screen, to the CES prompt in the bottom left corner, to the feedback modal in the center of the screen again - isn't that ideal.

Here's an idea that is based on discussions in the internal P2 pbIy4N-1Jn-p2. Instead of having the CES prompt in the bottom left corner, we can consider putting "give feedback" in the success modal (it can possibly be in a new Step 3 in the success modal). The idea or the message is around "Congratulations, you have successfully setup Google Listings and Ads! How easy was it?" - we want to get feedback right after users successfully completed their goals and _within the flow_ (without modals disappearing and reappearing, and without focus movement). 

If users happen to dismiss the success modal before reaching the Step 3, then we can display the CES prompt at the bottom left corner.

This may require a lil bit more effort (design and dev), so we can probably consider this as future improvement. 😄

**Comment by ianlin** [comment]
@ecgan Thanks for the useful suggestion! I also read the internal P2 `pbIy4N-1Jn-p2` and was really impressed by the discussion there. 👍 

> If users happen to dismiss the success modal before reaching the Step 3, then we can display the CES prompt at the bottom left corner.

I'd go for this at this stage because as you said using a `Step 3` for the `give feedback` requires more efforts for both design and development. I'm definitely looking forward to seeing this in the future. 😄 

@j111q 
> The "true" ideal would be for us to trigger the CES prompt at another point, like after the success modal is dismissed/closed and the user is looking at the product feed for the first time after setting up. But if I'm recalling correctly from our previous discussions, that wasn't possible.

I would love this to be implemented as well so I will try to do some research about the possibility of it.

**Comment by j111q** [comment]
Cool, let us know what you find!! And thanks again for flagging it. 

Just keep in mind that the CES prompt is _less important_ than the contents / buttons of the success modal. Getting their feedback through the CES prompt is good, but ideally should happen when "nothing else" is happening.
