### ISSUE TITLE
Variable Subscriptions attempting to sync

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#887]
### Describe the bug:
It's a pretty rare scenario, but if we have have Variable Subscription products saved, the variations are saved with the product type set to `variation`. With the Subscription plugin active, these are skipped (seems like a filter changes the product type there), however when we deactivate the Subscription plugin and sync all products, it still picks up those variations and tries to sync them in a batch.

The batch fails with the error:
```
action failed via WP Cron: The value of parent_wc_product must be an instance of WC_Product_Variable.
```

_Note: Even though just one product in the batch fails, the whole batch is stopped and none of those products are updated._
_Note2: The batch is retried with the same product set, but fails repeatedly until the error threshold rate is reached._

With the subscription plugin active those products are not included in the batch (because the product type doesn't match). To keep the behaviour consistent should we check the parent product type in the `is_sync_ready` function since those are stored as subscription_product it will automatically skipped those and the batch can continue.

### Expected behavior:
The batches to process and skip any subscription products (including it's variations).

### Steps to reproduce:
1. Activate Subscription plugin
2. Create a variable subscription product
3. Deactivate Subscription plugin
4. Sync all products (async) in connection test
5. View the failed scheduled actions and see the error "The value of parent_wc_product must be an instance of WC_Product_Variable"

**Comment by mikkamp** [comment]
When trying to sync the orphaned variation by ID. We can see that the `is_sync_ready` skips over the product because the parent is 0 here: https://github.com/woocommerce/google-listings-and-ads/blob/1.2.1/src/Product/ProductHelper.php#L280

But then when we get the visibility this isn't done which throws the exception:
https://github.com/woocommerce/google-listings-and-ads/blob/1.2.1/src/Product/ProductHelper.php#L317-L320

A quick fix would be to add the empty check in visibility, however then it would still fail the batch when process_item is called. It would be better to find a way to return false in `is_sync_ready` if it's a variation without a parent.

**Comment by nima-karimi** [comment]
I tested this issue with the https://github.com/woocommerce/google-listings-and-ads/pull/894 PR and even though the exception is still thrown, product syncing goes without disruption since we silently log the issue and skip the product.

> To keep the behaviour consistent should we check the parent product type in the is_sync_ready function since those are stored as subscription_product it will automatically skipped those and the batch can continue.

We would still fetch those subscription products from DB and try to sync them because once the subscription plugin is disabled, the product types are returned as a hard-coded `simple`. 

What happens is that the WC Product Data Store looks for the taxonomy term and returns `variable-subscription` but then `\WC_Product_Factory::get_product` tries to assign a class name to that product name which no longer exists and ends up assigning it `WC_Product_Simple`, which always returns a hard-coded `simple` as product type.

One way to resolve it would be to get the product types via the `\WC_Product_Factory::get_product_type` method, which always checks for the value in DB instead of getting the value from the product object.

However, since we already skip those products because they cause an exception, it might not be so urgent.

**Comment by mikkamp** [comment]
I think the solution in #894 is sufficient. This is a rare scenario since most customers that have these kind of products will have the plugin active. My main intent with this issue was to ensure that the syncing doesn't fail/halt when it encounters a product it is unable to sync.
