### ISSUE TITLE
Allow stores to mark themselves as an Adult-oriented account

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#956]
## Context
Google automatically detects an "adult" URL. When this happens, the store needs to mark themselves as an adult-oriented account, otherwise they can't create an account.

Proposed solution:
![Screen Capture on 2021-08-12 at 17-18-17](https://user-images.githubusercontent.com/65582817/129172160-1f6207b3-ea65-4b98-85ba-5987abceceab.gif)

Link to Figma: https://mc.a8c.com/pb/29f96/

## Out of scope
- User marking an account as "Adult" in settings, after setup is already complete 
- User changing an account from "Adult" to not-Adult.

h/t to @mikkamp and @shivanarrthine for helping to review the solution!

**Comment by mikkamp** [comment]
I did some further testing and scanning through the logs for this issue. The create Merchant Account call doesn't seem to fail on the terms in the website URL, but instead on the name that we provide when creating an account. We use the site title for this which can be set in WordPress > Settings > General.

```
[
	'name'       => 'My site name',
	'websiteUrl' => 'siteurl.com',
]
```

For reference the API can return the following error messages depending on how many terms the name contains:
```
[name] These terms are not allowed: 'xxx', 'yyy'
[name] The term 'xxx' is not allowed
```

Setting the flag as "adultContent" to true doesn't help when creating the account. It still fails with the same error message.

The name field is described in the documentation as: "Display name for the account"
Setting it to the site name is helpful for identifying the merchant account (although we don't use it when linking an account).

If a term is detected in the site name we might still benefit from confirming to enable the adultContent flag, but we'd also need to use a replacement name, is there a better alternative to use which wouldn't get flagged?

Also since it's not specific to the URL would we need to reword the message in the UI?

I've also tested verifying and claiming a URL with adult terms, which completes without any errors. As long as I change the site name I'm not required to mark it as adultContent.

**Comment by findingsimple** [comment]
> Setting the flag as "adultContent" to true doesn't help when creating the account. It still fails with the same error message....The name field is described in the documentation as: "Display name for the account"

Thanks @mikkamp, so to confirm - after testing more its actually to do with the account name set/used in the Merchant Center.

> If a term is detected in the site name we might still benefit from confirming to enable the adultContent flag, but we'd also need to use a replacement name, is there a better alternative to use which wouldn't get flagged?

That's a good thought, I can't think of anything we could guarantee was free of issue unless we used a number

**Comment by mikkamp** [comment]
> so to confirm - after testing more its actually to do with the account name set/used in the Merchant Center

Yes, we don't use it much in our extension because we would need to do multiple requests to get the names when listing all the accounts.

> I can't think of anything we could guarantee was free of issue unless we used a number

My initial thoughts would be to use something based on a date string (we also need to come up with a default when the site name is empty as this fails). Or alternatively since we get the exact terms back in the error message, we could use a filter to remove them from the string.

We already have a collection of words from the logs, although the full list isn't available, but we could use that to preemptively filter some of the words.

**Comment by j111q** [comment]
> If a term is detected in the site name we might still benefit from confirming to enable the adultContent flag,

Hmmmmmmm interesting. I gave this some thought - actually, **let's not enable the adultContent flag on the account** if it's not a compulsory step for them to create an account. We shouldn't assume ALL their products are Adult just based on a site name. We can rely on the Google product disapprovals to highlight if they need to set adultContent on their products/account, after they submit their product feed for review.

So the solution should be:
1. Detect an adult term in the Site Name
2. Rename the Account Name (I'm okay with either the date idea, or the filter to remove it)

IMO we don't need to alarm or confuse the user about any of the above^, it should happen behind the scenes, automatically.

Does this make sense?

**Comment by mikkamp** [comment]
> Does this make sense?

Yes that should work, it will greatly simplify the changes needed, since we won't need any changes in the UI.

**Comment by j111q** [comment]
Yes. Thank you @mikkamp!
